bitcoin/bips

- bip-0044.mediawiki
Add Encompass to the list of BIP-0044 compatible wallets.
> BIP-0044 - add a compatible wallet

- bip-0066.mediawiki
The Bitcoin Core tests in script_tests.cpp refer to these examples by number, but the text examples are in an unordered list, making them hard to follow.  This changes the list to an ordered (numbered) list.
CC: BIP author @sipa
> BIP66: Number Examples To Match Implementation Tests

- bip-0061.mediawiki
The reject code 0x12 is used for Version duplicate, but also when an input is already spent (bad-txns-inputs-spent)
> Reject code DUPLICATE also used for rejecting tx

- bip-0065.mediawiki
I added a section on the ability to freeze funds, updated link to go straight to the new bitcoin-dev mailing list archive, and added a section on implementations.
> BIP65: add sections on ability to freeze funds and implementations

- README.mediawiki
- bip-0101.mediawiki
Proposal to increase maximum possible block size, starting at 8MB
in January 2016 and increasing on-pace with technological growth to
8,192MB in twenty years.
> BIP 101 : maximum block size increase

- bip-0101.mediawiki
Bit thirty needs to be set to be compatible with Pieter's version proposal; I have no idea why I said 14.
And changed the description to "first, second... etc" to try to avoid "does numbering start with bit 0 or bit 1" confusion.
> Correct description of which version bits are set

- bip-0113.mediawiki
- bip-median-past-timelock.mediawiki
Following the announcement on the ML (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-August/010348.html).
TODO:
> BIP113: Median Past LockTime

- bip-0105.mediawiki
The voting mechanism did not previously account for BIP34.
> BIP105: Update to account for BIP34

- bip-0047.mediawiki
Specify procedure for extracting payment codes from notification transactions.
Add explicit check that payment code x values are valid for secp256k1
> BIP-47: Clarify decoding of notification transactions

- bip-0070/paymentrequest.proto
This resolves an incorrect link to `extensions.mediawiki` in the code comments of `paymentrequest.proto`.
> BIP70: Fix broken extensions registry link in code comment.

- bip-0069.mediawiki
`Randomly order` sound a bit like an oxymoron. Maybe `randomizing the order of` is better English?
> BIP-0069: [trivial] expression

- bip-0047.mediawiki
Previously specified version byte only produced the desired leading character if the check bytes were omitted
Thanks to TD from Samourai Wallet for pointing this out
> BIP-47: correct base58check version byte

- bip-0062.mediawiki
[Some folks are asking miners to deploy BIP 62](http://blog.coinkite.com/post/130318407326/ongoing-bitcoin-malleability-attack-low-s-high), but it isn't in a deployable state right now...
> BIP0062: Add a warning about its undeployable status

- bip-0032.mediawiki
The test vectors currently reference a "master", an ambiguous term with no single meaning in the BIP32 spec. The test vectors should instead reference the seed.
> Fix ambiguous reference to seed value in BIP32 test vectors

- bip-0047.mediawiki
The blinding factor used for notification transactions incorporates and outpoint being spent by the notification transaction.
This ensures that blinding factors will always be unique, even if a user sends a notification transaction to the same recipient multiple times while spending funds from the same address.
Since some common EC libraries have ECDH functions that only return the x value of the resulting point, only use the x value for calculating scalar shared secrets.
> Improve ECDH and blinding factor calculations

- bip-0120.mediawiki
Spelling:
"neccesarily" => "necessarily"
"scipts" => "scripts"
One small improvement for clarity:
"another" => "a different"
> Spelling fix and small clarification for BIP 120

- bip-0102.mediawiki
- bip-XX-2mb.mediawiki
A minimum-increase BIP alternative.
> BIP 102: Increase block size limit to 2MB

- bip-0065.mediawiki
BIP65 is being deployed by IsSuperMajority. Updating this BIP to reflect this fact.
> Update deployment for BIP65

- bip-0065.mediawiki
Add recommendation that SPV clients validate nVersion deployment rules to prevent the acceptance of invalid blocks after the 95% threshold has been reached.
> BIP65 spv clients

- bip-0099.mediawiki
This BIP attempts to classify all possible scenarios for consensus rule changes (soft/hard forks) as well as recommending a deployment path for each of them.
It also contains code proposing a first uncontroversial hardfork that conclusively fixes the timewarp attack: https://github.com/bitcoin/bitcoin/compare/0.11...jtimon:hardfork-timewarp-0.11
The recommended activation conditions for uncontroversial hardforks are still being discussed in http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-July/009731.html
More general discussion about the BIP can still continue in http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-June/008936.html
> BIP99: Motivation and deployment of consensus rule changes

- bip-0001.mediawiki
Clarified about BIP number assignment (not to self-assign, how numbers get assigned specifically).
> BIP-0001: Updates

- bip-0112.mediawiki
Clarification on retroactive invalidation and improvement to language.
> BIP-0112 minor revision to text.

- bip-0112.mediawiki
For https://github.com/bitcoin/bitcoin/pull/6564
> BIP112: Update document to match implementation

- README.mediawiki
- bip-0103.mediawiki
> Bip 103 squashed

- README.mediawiki
- bip-0001.mediawiki
Previously BIP-0001 listed in its header preamble that is was a "Standards Track"
type proposal. This conflicts with both its own definition of "Standards Track"
proposal as well as the type listed in PEP-0001 of which BIP-0001 is based on.
Defitions of each type of proposal:
A Standards Track BIP describes any change that affects most or all Bitcoin implementations.
An Informational BIP describes a Bitcoin design issue, or provides general guidelines or information to the Bitcoin community, but does not propose a new feature.
A Process BIP describes a process surrounding Bitcoin, or proposes a change to (or an event in) a process.
Specifically: "Any meta-BIP is also considered a Process BIP."
Based on these definitions BIP-0001 should have always been labeled as a "Process" BIP and this …
> BIP-0001 Should be labeled as "Process" Type

- bip-0112.mediawiki
Mainly for correcting the typo: and->or
> Corrections with the conditions for script failure

- bip-0047.mediawiki
Update explanations to resolve unclear sections, based on recent feedback.
> BIP47 clarifications

- bip-0065.mediawiki
With https://github.com/bitcoin/bitcoin/pull/6351 merged (and subsequent backport's), it would seem this status is fitting?
> BIP65: Change to accepted status

- bip-00nn.mediawiki
This is the amended Normalized Transaction ID BIP previously discussed
on the mailing list. Since the discussion on the mailing list there
have been some major changes, for one the BIP changed from requiring a
hard-fork to a much easier soft-fork (thanks sipa for helping me
figure out how).
The normalized transaction IDs are computed on a stripped version of
the transaction, in which all the malleable parts, i.e., the
signatures, where removed. This solves malleability in a simple and
clean way.
Unlike the original proposal, this version does not use the normalized
transaction IDs on a network level, instead they are used solely when
signing and checking signatures. Normalized transactions are swapped
in on-demand when using a new opcode OP_CHECKSIGEX and are tracked in
the UTXO, no …
> BIP 140: Normalized transaction ID

- README.mediawiki
- bip-opt-in-rbf.mediawiki
@petertodd and I present the following proposed BIP describing opt-in full-RBF signaling, as requested in the [2015-12-03 bitcoin-dev IRC meeting](http://www.erisian.com.au/meetbot/bitcoin-dev/2015/bitcoin-dev.2015-12-03-18.59.html).
Opt-in full-RBF has previously been [discussed on the mailing list](http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-November/011783.html) and support for it has been [added to Bitcoin Core](https://github.com/bitcoin/bitcoin/pull/6871), so I humbly request the assignment of a BIP number from the BIP editor, @gmaxwell.
Upon receipt of the number assignment and fixing any initial issues found with this proposed text, I will post a copy of this BIP to the mailing list for interested developers to read.
> BIP 125: Opt-in Full Replace-by-Fee Signaling

- bip-codeshark-jl2012-segwit.mediawiki
> BIP 141: Segregated Witness (Consensus layer)

- bip-0044.mediawiki
I suggest that we add copay to thie list of compatible wallets for Bip44 as they use the Bip44 path for key derivation
> add copay link to bip44 compatible wallets list

- README.mediawiki
We changed it in the BIP doc itself, but not the index.
> Minor: Fix BIP65 status in README

- bip-0141.mediawiki
- bip-0142.mediawiki
- bip-0143.mediawiki
- bip-0144.mediawiki
Revised based on the latest codebase:
https://github.com/sipa/bitcoin/commits/segwit2
> BIP141: New commitment structure, sigop limits, etc

- README.mediawiki
- bip-0083.mediawiki
Proposed deterministic key tree structures suffer from the limitation that once a hierarchical level is used to derive signing keys, we can no longer nest deeper levels. This BIP proposes a solution to this problem.
> BIP 83: Dynamic Hierarchical Deterministic Key Trees

- README.mediawiki
- bip-0141.mediawiki
- bip-0142.mediawiki
- bip-0143.mediawiki
- bip-0144.mediawiki
BIP141: New witness program definition
BIP142: Title change; new address definition
BIP143: Title change and update reference implementation
BIP144: Update reference implementation
> New witness program definition in BIP141, and related revision in 142 - 144

- bip-0102.mediawiki
> BIP 102: update to match implementation

- bip-0142.mediawiki
Was stumbling over this while reading the BIP.
> Fix little typo in p2wpkh address creation

- README.mediawiki
- bip-0080.mediawiki
- bip-0081.mediawiki
Two informational BIPs are submitted for voting pool HD wallets.
This wallet format follows the BIP43 recommendation to use reserved BIP numbers to avoid namespace collisions.
The purpose of the wallet formats is to efficiently implement multisig, FIFO cold storage for bulk bitcoins and for colored bitcoins.
> BIP 80 & 81: Hierarchies for Voting Pool Deterministic Multisig Wallets

- bip-0141.mediawiki
Update non-upgraded wallet description; remove BIP142
> BIP141 Non-upgraded wallet description

- bip-0141.mediawiki
> BIP141: Add 520 bytes witness stack limit

- README.mediawiki
- bip-0074.mediawiki
PaymentRequests currently support any valid script
serialized in the PaymentDetails protocol buffer.
Zero value outputs are ignored and not included in the
transaction. This means that OP_RETURN scripts are
currently supported but they must have a > zero value,
effectively destroying the value assigned to that output.
This BIP allows zero value PaymentRequest outputs ONLY
if the script is an OP_RETURN.
> BIP74 Draft

- bip-0034.mediawiki
The height has a sign bit so a 3-byte height should last for 150 years instead of 300
> BIP34 correction: the height has a sign bit

- README.mediawiki
- bip-0109.mediawiki
Thanks to @luke-jr for promptly assigning a BIP number.
This was discussed on the bitcoin-dev mailing list, but that discussion went sideways fairly quickly (as do all discussions about hard forks, it seems). It is implemented in Bitcoin Classic.
> BIP109:  BIP102 variation for a 2mb block size bump

- bip-0050.mediawiki
Bitcoin Core didn't exist until 0.9.
> Correct typo

- bip-0044.mediawiki
Some of the source will be released soon.
> Adding crypzo to BIP44 supported wallets

- bip-0069.mediawiki
We might switch to the BitcoinJS implementation in the future.
cc @kristovatlas
> BIP 69: Add link to Blockchain.info implementation

- bip-0047.mediawiki
Results obtained upon implementing BIP47 for Samourai Wallet. Payment codes are calculated assuming v1 specification without use of BitMessage. Also assumes notification transaction from Alice to Bob has been sent.
> Add link to BIP47 test vectors

- bip-0069.mediawiki
Hi, adding a link to recently merged golang implementation of bip 0069.
> add link to btcsuite implementation of bip 0069

- bip-0009.mediawiki
I added explicit parameters for deployment at the beginning of the specification. I think this greatly clarifies the spec for someone approaching it for the first time.
We've decided for now not to consensus-enforce the bit states, making the RFC language that had been previously proposed a bit superfluous. The only thing that remains consensus-enforced is the moment of activation which should be clear from context.
> Added clarifications to BIP0009.

- bip-0133.mediawiki
> [Bip 133] Fix typos

- bip-0001.mediawiki
This pull request contains two trivial changes for BIP1:
* Formatfix the "auxiliary files" section, and also consolidating the sentence about images into the section about auxiliary files.
* Typofix "sumission" -> "submission" in the changelog section.
and two less-than-trivial changes:
* Make "BIP Header Preamble" a subsection of "BIP Formats and Templates".
* Make "auxiliary files" a subsection of "BIP Formats and Templates".
> BIP1: Formatfix for auxiliary files section and a small typofix

- bip-0044.mediawiki
The original link was broken use http://www.crypzo.com to get the redirect
> Crypzo has changed name to CoinVault

- bip-0141.mediawiki
Now we know we will use BIP9 version bits, remove references to ISM() and leave TDB
as was done with BIP68,112 and 113.
> Remove deployment section

- bip-0141.mediawiki
This is the result of feedback from the general public.
Basically we know we're using BIP9 deployment, but we haven't decided on the deployment variables `starttime`, `timeout`, and `bit`. I'm providing a template here so we can file them out once known.
> Clarify what remains "to be decided"

- bip-0047.mediawiki
Introduce the terms 'designated input' and 'designated pubkey' for clarity
Update reference link for outpoint to a more canonical source to resolve ambiguity regarding the binary representation of txids.
Based on feedback from @SamouraiDev
> BIP-0047: Clarify usage and format of outpoints

- bip-0143.mediawiki
This PR clarifies the semantics change when ANYONECANPAY is used with SINGLE, with other minor clarifications
> BIP143 clarifying semantics of ACP|SINGLE

- bip-0143.mediawiki
Minor typo fix for BIP143, "inculding" -> "including".
> BIP143: fix typo ("including")

- bip-0141.mediawiki
The byte representation of "<0 <32-byte-hash>>" is "0x220020{32-byte-hash}"
What was listed here would be the byte representation of "0 <32-byte-hash>". The text explains that there is only one item in scriptSig, so I'm guessing the byte representation is wrong. Also the corrected byte representation would produce the same sig/pubkey described in P2WSH after following the bip16 rules.
> fix BIP141 nested P2SH scriptSig byte representation

- bip-0144.mediawiki
As per the meeting: http://www.erisian.com.au/meetbot/bitcoin-core-dev/2016/bitcoin-core-dev.2016-04-28-19.00.html
Updates BIP 144 to specify the use of the NODE_WTINESS service bit instead of a havewitness message.
> Update BIP 144 'havewitness' to service bit

- README.mediawiki
- bip-0151.mediawiki
The Bitcoin network does not encrypt communication between peers today. This opens up security issues (eg: traffic manipulation by others) and allows for mass surveillance / analysis of bitcoin users. Mostly this is negligible because of the nature of Bitcoins trust model, however for SPV nodes this can have significant privacy impacts [1] and could reduce the censorship-resistance of a peer.
> BIP 151: Peer-to-Peer Communication Encryption

- bip-0009.mediawiki
A BIP in state STARTED that did not reach the threshold would disappear instead of stay in STARTED.
The hex error made me looking for a bug for almost an hour after copy pasting the hex values.
> Error in BIP0009 code example

- bip-0141.mediawiki
The maximum witness program size is increased from 32 to 40 bytes. This provides extra space to specify script version (for originally 16 upgradable versions to up to 16 * 2 ^ 64)
> BIP141: extend max witness program size to 40 bytes

- bip-0009.mediawiki
The threshold for should be ≥1916 for mainnet, ≥1512 for testnet.
https://github.com/bitcoin/bitcoin/blob/v0.12.1/src/versionbits.cpp#L69
https://github.com/bitcoin/bitcoin/blob/v0.12.1/src/chainparams.cpp#L84
https://github.com/bitcoin/bitcoin/blob/v0.12.1/src/chainparams.cpp#L177
> Clarify BIP9 threshold

- bip-0009/assignments.mediawiki
This PR updates the BIP9 bit assignments list since the `segwit` deployment is now active on testnet. It also changes the `csv` testnet activation height from "770111" to "770112" since that is the first block where the deployment is active.
> Update BIP9 assignments list

- bip-0141.mediawiki
Might seem superfluous,  but I would find the clarification meaningful,  even if the given literal is inherently 1 byte.
> bip141: clarify that marker is 1 byte

- bip-0151.mediawiki
HKDF seems to be the better approach to derive symmetric cipher keys from the ECDH shared secret.
Discussion: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-July/012878.html
ping @Roasbeef @sipa @gmaxwell @zooko
> [BIP151] Switch from plain HMAC_SHA512 KDF to HKDF

- bip-0021.mediawiki
Add the library [BitcoinPaymentURI](https://github.com/SandroMachado/BitcoinPaymentURI).
> Add a library reference

- bip-0039.mediawiki
This is now in the default wallet.
> BIP 39: remove "public beta" from blockchain.info link

- bip-0141.mediawiki
The term 'block cost' led to confusion about the unit that it is expressed in, in that it expressed monetary cost. Change it to a more general term 'block weight'.
This was discussed in the [2016-07-14 Bitcoin Core developer meeting](http://www.erisian.com.au/meetbot/bitcoin-core-dev/2016/bitcoin-core-dev.2016-07-14-19.00.html).
> bip141: Change 'block cost' to 'block weight'

- bip-0141.mediawiki
@sipa 
1. Make the use of "witness program" consistent
2. Fix: P2WSH script has a 10000 byte limit
3. Remove the mention of extending 32 bytes witness program with softfork
> BIP141 fix

- bip-0151.mediawiki
~~This clarifies that the ciphertext payload length is meant to update the AEAD as AAD. OpenSSH does this, but in a naive way, [as seen here][1] (aadlen is 4 -- poly1305_auth is called on both size and payload).~~
~~Although the payload length _is_ AAD, OpenSSH violates [both][2] [RFCs][3] by not including the AAD length (or the ciphertext length) in the MAC before finalization. This change to the bip includes the size explicitly as AAD.~~
Update: Nevermind the above change. I confused myself by reading the openssh code too much (AAD not necessary due to bip151's encrypted size).
This change also explicitly mentions sequence numbers are meant to be uint32's which are allowed to overflow. This is in keeping with [openssh behavior][4]. I don't think having a 64bit sequence provides any …
> BIP151: Clarifications on sequence numbers.

- bip-0151.mediawiki
The current re-keying procedure does allow an attacker knowing the current symmetric cipher key while **not** knowing the session-id (derived from the ECDH secret) to "survive" the re-keying.
This will slightly increase the prediction resistance.
Also includes a ugly typo in the `hkdf` key. Reported by @ccjj.
cc: @ccjj
> [bip151] slightly increase robustness of the re-keying

- bip-0039.mediawiki
BipMnemonic is a ruby gem to generate BIP-39 compliant Mnemonic Words from specific entropy or random entropy of `n` bits and also to generate the BIP-32 seed from the BIP-39 Mnemonic.
It also lets you convert the Mnemonic back to the entropy.
> Adding ruby implementation to Other implementation

- bip-lows.mediawiki
This BIP specifies proposed changes to the Bitcoin transaction validity rules to restrict signatures to using low S values.
> BIP 146: Low S values signatures

- README.mediawiki
- bip-0146.mediawiki
NULLDUMMY is a trivial softfork to fix malleability related to the extra stack element consumed by CHECKMULTISIG(VERIFY). NULLDUMMY is probably more important than LOW_S since without that an attacker may replace the stack element with any value.
> BIP146: change title and add NULLDUMMY rules

- bip-0112.mediawiki
CHECK(MULTI)SIG should be used.
> BIP112: fix example

- bip-0141.mediawiki
Virtual transaction size and Transaction weight are not consensus-critical, but are used in bitcoin-core IsStandard() policy, and v0.13.0+, RPCs calls return virtual transaction size instead of serialized transaction size. Although non-normative, BIP 141 should include definitions for these concepts.
https://github.com/bitcoin/bitcoin/pull/8747 is a PR to fix the RPC help text to refer to virtual transaction size instead of transaction size.
> Update BIP 141 to include definition of Virtual transaction size and Transaction weight

- bip-p2sh-accounts.mediawiki
A derivation scheme similar to BIP44 for the upcoming P2WPKH-nested-in-P2SH addresses.
The test vectors aren't finished yet, as I choose to have the BIP-number as base path (like BIP44) in it. I'll update them as soon as this gets a preliminary number assigned.
> BIP 49: Derivation scheme for P2WPKH-nested-in-P2SH based accounts

- bip-0002.mediawiki
The section about the BIP status field only defines
"Replaced or Obsolete (which is equivalent to Replaced)",
so remove "Superseded" for clarity.
> BIP2: Remove Superseded from choices for Status

- bip-0143.mediawiki
Developers must pay attention to the BIP143 spec that `FindAndDelete` is not used. This gives some examples. Also edited the descriptions for `CODESEPARATOR` to avoid misunderstanding
> Add examples to show FindAndDelete is not used in BIP143

- bip-0049.mediawiki
Just noticed that I used the wrong coin-type for the derivation path (0' for prodnet instead of 1' testnet).
Fixed it and recalculated the test vectors.
> BIP49 - fix wrong cointype for test vectors - use m/49'/1'/0' for testnet

- bip-0152.mediawiki
Corresponding bitcoind change is: https://github.com/bitcoin/bitcoin/pull/9058 commit `Modify getblocktxn handler not to drop requests for old blocks`.
> Allow block responses to getblocktxn requests

- bip-0123.mediawiki
- scripts/buildtable.pl
Also: It's unclear where to draw the lines for API/RPC. The previous draft had Stratum (which is being removed here since there sadly isn't a BIP yet) as Applications and GBT as API/RPC, when both protocols serve the same fundamental purpose.
Need to get this cleaned up to move forward on both it as well as BIP 2...
@CodeShark
> BIP 123: Clarify how used with non-Standards BIPs, and update list

- bip-0152.mediawiki
This does not change any implementation details of the protocol, only encourages SPV client authors to avoid high-bandwidth mode due to lack of validation.
> Clarify SPV node usage of BIP 152

- bip-0152.mediawiki
This clarifies some unstated details previously, as well as defines some previously undefined behavior.
> Clarify BIP 152 interaction with classic relay mechanisms

- bip-0032.mediawiki
These additional test vectors will ensure all future implementations are compliant with bip32.
See https://github.com/iancoleman/bip39/issues/58 and https://github.com/bitpay/bitcore-lib/issues/47
Possibly these test vectors may be useful also:
[bitcoinjs-lib test for this issue](https://github.com/bitcoinjs/bitcoinjs-lib/blob/4b4f32ffacb1b6e269ac3f16d68dba803c564c16/test/fixtures/hdnode.json#L180)
[bitcore-lib test for this issue (pending merge)](https://github.com/bitpay/bitcore-lib/pull/97/commits/b79a9b274ae8b48701daf5a1284e4f9035c3df0d#diff-c78032f7e0957dc3eebfc586843c6430R224)
> BIP 32: Test vectors for leading zeros

- README.mediawiki
- bip-0171.mediawiki
- bip-xchgrate.mediawiki
Discussion: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-March/013660.html
> BIP 171: Currency/exchange rate information API

- bip-0148.mediawiki
Includes basic refactor.
No-need to calculate the GetMedianTimePast() value twice.
> Stop UASF enforcement if SegWit has IsLockedIn state.

- bip-0066.mediawiki
The DER specification link in BIP66 seems to be dead. 
I could not find the 2008 pdf in any [archive](http://archive.is/Yxwln) pages. Current version is available at the url: https://www.itu.int/rec/T-REC-X.690-201508-I/en but they seem to be ruining these urls with every update, so I changed the url to the listing page.
Optionally info could be added that the BIP is based on the 2008-11 version, but the BIP only touches the basics of the encoding which I think shouldn't change.
> fix dead link in BIP66

- bip-0039/bip-0039-wordlists.md
* "there not must" => "there must not"
* "exemple" => "example"
* Capitalize "French", "Italian"
* Trailing whitespace removal.
> bip-0039-wordlists : Typos, capitalization and trailing whitespace.

- README.mediawiki
In the table there are some BIPs with a status of `Active`, and others
with a status of `Final`. Just wanted to submit this slight text change
for review to the README to indicate that both mean a BIP is formally
accepted.
> readme: Clarify status for formally accepted BIPs

- bip-0091.mediawiki
This should make BIP91 activation faster and less likely to conflict with BIP148.
> Update BIP91 confirmation window and enforcement.

- bip-0091.mediawiki
This gives a ~2 day upgrade period for miners to enforce mandatory signalling after lock-in and makes activation potentially faster.
> Use a smaller deployment period for BIP91 but don't enforce until active.

- bip-0159.mediawiki
Bit 6 and 8 seems to be kidnapped by BCash and SW2x (without following the BIP process).
Therefore I consider 0-8 taken and leave 9 reserved and start at bit 10 for limited services.
> Set bit 10 and 11 for NODE_NETWORK_LIMITED_LOW, HIGH

- bip-0159.mediawiki
The current BIP couples the two `NODE_NETWORK_LIMITED_*` bits by setting the state as undefined when signaling both bits. Ideally we can treat them independently which means signalling NODE_NETWORK_LIMITED_HIGH will always require to signal `NODE_NETWORK_LIMITED_LOW` as well.
The downside for this simplification is that we loose the possible third state (both bits set).
> Allow to signal both bits and treat them independently

- bip-0144.mediawiki
Fix typo "inefficinent" => "inefficient" in BIP 144
> Correct typo in BIP 144

- README.mediawiki
- bip-0159.mediawiki
This removes the split between NODE_NETWORK_LOW|HIGH and reduced the specification to a single signalling bit (bit 10) NODE_NETWORK_LIMITED with a min height of 288 blocks.
The implementation has already been updated: https://github.com/bitcoin/bitcoin/pull/10387
> Remove second service bit from NODE_NETWORK_LIMITED/BIP159

- bip-0032.mediawiki
Elliptic curve digital signature algorithm
> typo 'ECSDA' changed to correct 'ECDSA'

- bip-0173.mediawiki
* `a12uel5l`: vector added to demonstrate that it and its uppercase version, `A12UEL5L` are both valid and treated as equal. `segwit_addr.bech32_encode('a', [])`
* `10a06t8`: vector added to demonstrate that a combined empty HRP and empty data encode to a valid Bech32 string. `segwit_addr.bech32_encode('', [])`
* `1qzzfhee`: vector added to demonstrate that an empty HRP encodes to a valid Bech32 string. `segwit_addr.bech32_encode('', [0])`
* `pzry9x0s0muk`: vector moved to a new section as it is misleading in the current section because "No separator character" can not affect checksum validity because the separator char is not used to compute the checksum.
```
>>> segwit_addr.bech32_create_checksum('', [1,2,3,4,5,6])
[15, 16, 15, 27, 28, 22]
>>> segwit_addr.bech32_verify_checksum('', …
```
> bip-0173: test vectors, HRP, and casing requirements updates

- bip-0175.mediawiki
* Standardizing spelling of "payer".
* In examples:
- Added headings
- Separated "document 1:" label from the contents which are actually hashed (eg "baz").
* Misc spelling mistakes.
@omarshibli
> BIP 175 Improvements

- bip-0152.mediawiki
In all implementations and in the intended reading of "existing chain", cmpctblock messages should never be sent without having fully-validated every previous block it builds on, and it being a new candidate tip. Clarify that slightly more for the avoidance of doubt.
> Clarify cmpctblock previous block requirement

- bip-0039.mediawiki
- bip-0175.mediawiki
Based on community feedback we are adding the payment_base as an extra layer of security and prevent mathematically possible contract forgery, with that being said it worth mentioning that this scenario could be very hard due to the fact that this BIP uses BIP32 derivation mechanism which uses hmac-sha512 and the fingerprint of pubkey - chain code.
> Adding payment_base to the derivation path as an extra step of security 

- bip-0125.mediawiki
Grouped the two sections explaining the fee evaluation, then removed a redundant clause in the middle of the latter paragraph that confused the meaning.
@harding @petertodd ping authors
> Slight clarification for replacement implementation

- bip-0173.mediawiki
I can't find much about bech32 anywhere, before March 2017.
Based on the date of this commit, I think there is a typo in the date. https://github.com/sipa/bech32/commit/52b5a0fa6d3174c4150393fb7d6b58d34b4f5e0b
> BIP-173: fix typo in "Created" date

- bip-0159.mediawiki
@jonasschnelli 
Changes:
* The last section mentions "thresholds", while only a single threshold of 244 is specified in the bip. Clarify by changing to "threshold"
* Remove internal Bitcoin Core implementation detail. This is not relevant for a bip.
* Remove word "additional" when referring to safety buffer, since the safety buffer is the only buffer and not an additional one.
* Remove empty section "references"
* Add missing link to signaling implementation.
> bip159: Clarify that there is only one threshold

- README.mediawiki
- bip-0173.mediawiki
I believe that the BIP173 standard is complete and won't functionally change anymore. As required by BIP2, I believe there are community plans to progress it to final (given that multiple wallet implementations support or plan to support it).
> Progress BIP173 to Proposed

- bip-0117.mediawiki
The example scripts in BIP 117 presently use an outdated form of the MERKLEBRANCHVERIFY opcode. This patch updates them to the most recent version of the specification.
> BIP-0117: Correct the examples to use the most recent version of MERKLEBRANCHVERIFY

- bip-0117.mediawiki
This allows for more compact direct encoding of scripts of the form "pick 2 of 3 spend conditions" without enabling witness malleability in expected use cases as the components would still be checked against a pre-committed hash tree.
> BIP-0117: Change semantics of multi-element tail call to not require stack elements to be exactly 520 bytes in size

- README.mediawiki
- bip-0157.mediawiki
- bip-0158.mediawiki
This is a revision of #609 that is intended as a replacement due to the number of substantial changes. Test vectors will be added once the BIP has been reviewed by the community and the reference implementation is updated.
This BIP describes a new light client protocol in Bitcoin that improves upon currently available options. The standard light client protocol in use today, defined in BIP 37, has known flaws that weaken the security and privacy of clients and allow denial-of-service attack vectors on full nodes. The new protocol overcomes these issues by allowing light clients to obtain compact probabilistic filters of block content from full nodes and download full blocks if the filter matches relevant data.
New P2P messages empower light clients to securely sync the blockchain without …
> BIPs 157 & 158: Block Filtering stuff

- bip-0065.mediawiki
Current text:
> Using the same scriptPubKey **from** as in the Two-factor wallets example solves both these issues.
Proposed text:
> Using the same scriptPubKey **form** as in the Two-factor wallets example solves both these issues.
> Fix single typo in BIP65 ("from" -> "form")

- bip-0039.mediawiki
I added a BIP39 Swift implementation link.
> Add BIP39 Swift implementation link

- README.mediawiki
- bip-0120.mediawiki
- bip-0121.mediawiki
There is an inherent problem with BIP120, Proof of Payment: If there is a soft fork, a server that verifies PoPs will accept a PoP as valid without checking any of the new Bitcoin rules.
For example, a server will be fooled by a segwit transaction, because the server doesn't have a witness to verify and consequently will accept any PoP with an empty scriptSig.
Since BIP121 depends on BIP120, that has to go too.
> Withdrawing BIP120/121 due to security issues during soft-forks

- bip-0045.mediawiki
"it's" is the contraction of "it" and "is". "its" should be used for ownership
> fix grammar error

- bip-0098.mediawiki
Changes:
least <- lest
hashes <- hashses
addendum <- ammendum
> [trivial] Correct typos in BIP 98

- bip-0158.mediawiki
In this commit, we modify regular filter construction slightly.  Rather
than including each pushed data in the script, we instead just include
the script directly, which will eventually be hashed. The rationale for
doing this is two-fold:
* Most scripts today and in the foreseeable future will just be a
commitment.
* Including only the script itself and not the hash of the script
reduces the worst case filter size. Otherwise, an attacker could
include a bunch of 2 byte push datas and blow up the filter size for
all nodes.
> BIP158: include the direct pkScript rather than its data pushes

- bip-0009/assignments.mediawiki
Second row was created with an incorrect extra empty cell
> BIP 9: Misplaced table cells typo

- bip-0174.mediawiki
Clarifies that global data fields redeem scripts, witness scripts,
and hd keypaths can be used for data necessary for both the inputs
and outputs of the transaction.
> BIP 174: Clarify that global data can be for inputs and outputs

- bip-0066.mediawiki
BIP author: @sipa
Recently, a developer learning about Bitcoin contacted me with some questions about BIP66 and I discovered through our conversation that he wasn't aware of what I believe is this important context for the soft fork.  I sent him a link, but I'd like to propose linking to it directly from the BIP for the historical record.
I know modifying *final* BIPs is frowned upon, so if this is unacceptable, I'll add it instead to the wiki page indicated by the Comments-URI field.
> BIP66: link to disclosure of consensus failure bug

- README.mediawiki
- bip-0090.mediawiki
#478 added a label to BIP 90 that I disagree with.  While the term "hard fork" is sometimes used in the way defined in BIP 123, it also is used by many -- including the BIP 123 author -- to refer to consensus changes that require network-wide coordination in deployment to avoid a chain split[1], which is untrue for BIP 90.
As the whole purpose of this BIP is explain the type of consensus change that was made and point out that the network split risk is minimal, I don't accept the label "hard fork" as a useful or correct designation, and I think it does a disservice to our collective understanding of consensus changes to try to apply a label like this.
--
[1] From https://medium.com/@elombrozo/forks-signaling-and-activation-d60b6abda49a:
> Since hard forks loosen or eliminate existing …
> Remove 'hard fork' designation on BIP 90

- bip-0173.mediawiki
SLIP-0173 lists registered human-readable parts for BIP-0173, keeping the BIPs free of other cryptocurrency information. This echoes SLIP/BIP-0044 with registered coin types for HD wallet derivation paths.
> BIP 173: Adds link to SLIP-0173

- bip-0199.mediawiki
The sentence "Both parties can now construct the script and P2SH address for the HTLC." was broken with part appearing below the list item.
> BIP-199 Fix list formatting

- bip-0157.mediawiki
- bip-0158.mediawiki
With filter sizes at ~2% of block size, reducing `getcfilter` request size to 100 corresponds to a response with equal bandwidth to ~2 blocks.
> Tweaks to BIP 157/158

- bip-0112.mediawiki
The sequence is relative to the input, not the transaction. This may cause confusion
> BIP 112: fix typo 

- bip-0310.mediawiki
- bip-stratum-extension.mediawiki
Hi,
This proposal went formally through the mailing list: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-May/015978.html without any further discussion. Currently, this extension has been implemented by multiple pools. I would like to kindly ask for BIP # assignment and have this merged into upstream bips.
Best regards,
Jan Capek
> BIP 310: Stratum protocol extensions

- README.mediawiki
- bip-0322.mediawiki
Formatted version: https://github.com/kallewoof/bips/blob/bip-generic-signmessage/bip-0322.mediawiki
> BIP 322: Generic Signed Message Format

- bip-0159.mediawiki
The threshold seems to be 288 (2 * 144).  
https://github.com/jonasschnelli/bitcoin/blob/de74c625833bba8d8171a2d0dd6ede2e9d5da88b/src/validation.h#L207
> bip-0159: Fix NODE_NETWORK_LIMITED threshold

- bip-0125.mediawiki
It's been reported that the double negative in rule 2 is confusing people (including myself, on re-read).  This PR revises out both negatives and, I believe, significantly improves clarity.
For reference, this document was based on the implementation in Bitcoin Core 0.12.0, which includes [these lines](https://github.com/bitcoin/bitcoin/blob/v0.12.0/src/main.cpp#L1134):
```cpp
for (unsigned int j = 0; j < tx.vin.size(); j++)
{
// We don't want to accept replacements that require low
// feerate junk to be mined first. Ideally we'd keep track of
// the ancestor feerates and make the decision based on that,
// but for now requiring all new inputs to be confirmed works.
if (!setConflictsParents.count(tx.vin[j].prevout.hash))
{
// Rather than check the UTXO set - potentially expensive -
// …
```
> BIP125: rephrase rule 2 for clarity

- bip-0174.mediawiki
Being new to the spec, I had to reread this multiple times to understand it. Ordering the sentences according to scope makes it easier to grock.
@achow101
> Flipping the sentence order here for simplicity.

- bip-0084.mediawiki
The version bytes to produce "zpub" and "zprv" were not specified originally.
@prusnak
> BIP-84 - Add Version Bytes Section

- bip-0322.mediawiki
Simplifies BIP-322 to ONLY address signing/verifying a message, removing traces of proof-of-funds. Also adds some missing fields that were asked for, such as lock time and sequence.
The intention is to make a separate BIP which builds on top of this one for the proof of funds part.
Edit: I am still trying to figure out this and a separate BIP which addresses the proof of funds part. Not ready for merging yet.
> [WIP] bip-322: strip out proof-of-funds related stuff and fix several issues

- README.mediawiki
- bip-0197.mediawiki
Hello all,
This proposal went through the mailing list: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2019-March/016805.html without any further discussion. Currently this proposal has been implemented by in the ChainAbstractionLayer (https://github.com/liquality/chainabstractionlayer/tree/dev). I would like to kindly ask for BIP # assignment and have this merged into upstream bips. 
Cheers,
Matthew Black
> BIP 197: Hashed Time-Locked Collateral Contract

- README.mediawiki
- bip-0127.mediawiki
- bip-0174.mediawiki
(submitted to bitcoin-dev, awaiting approval)
> BIP 127: Simple Proof-of-Reserves Transactions

- README.mediawiki
- bip-0151.mediawiki
The BIP151 proposal does have some practical downsides and thus a new proposal has been made (https://gist.github.com/jonasschnelli/c530ea8421b8d0e80c51486325587c52)
> Withdraw BIP151

- README.mediawiki
- bip-0136.mediawiki
This proposed BIP was posted to the mailing list just under two months ago. As there has been no serious objections, (unfortunately no mailing list feedback at all), I wish to formally ask for a BIP number to be assigned to our proposal.
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-May/014396.html
> BIP 136: Bech32 Encoded Tx Position References

- bip-0174.mediawiki
Adds a global type for xpubs as discussed on the bitcoin-dev mailing list: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2019-April/016894.html
> bip174: add global xpub field

- README.mediawiki
- bip-0155.mediawiki
- bip-XXXX.mediawiki
Proposal for wider v2 address messages.
Last time this went around (as a github gist) there were some considerations still to be discussed, for lack of a working mailing list I'll post them here:
* ''Client MAY store and gossip address formats that they do not know about'': does it ever make sense to gossip addresses outside a certain overlay network? Say, I2P addresses to Tor? I'm not sure. Especially for networks that have no exit nodes as there is no overlap with the globally routed internet at all.
* Lower precision of <code>time</code> field? seconds precision seems overkill, and can even be harmful, there have been attacks that exploited high precision timestamps for mapping the current network topology.
* (gmaxwell) If you care about space time field could be reduced to 16 bits …
> BIP 155: addrv2 BIP proposal

- bip-0144.mediawiki
At least Bitcoin Core requires the old serialization format in that case, so to pretend that it is optional will only lead to confusion.
> BIP 144: Old serialization format must be used on empty witness

- README.mediawiki
- bip-0049.mediawiki
it gets used by electrum, trezor and other wallets
> Set Status für BIP49 to 'Final'

- bip-0158.mediawiki
The current link references https://github.com/Roasbeef/btcutil/tree/gcs/gcs which is an out of date branch.
I've replaced this with https://github.com/btcsuite/btcutil/blob/master/gcs
> BIP 158: Updated Golomb-Rice Coded sets Reference Implementation link

- bip-0322.mediawiki
* Remove ProveFunds purpose (with a note about extensibility) and fix the serialization format.
* Add legacy fallback for P2PK(H) addresses, and flip "Backwards Compatibility" section.
* Note about signing using privkeys directly.
* Add Test Vector
> BIP-322 updates

- bip-0178.mediawiki
That opinion was unnoticed for more than a month now, maybe this helps getting other arguments that support BIP-0138.
> Updated BIP-0138 Comments-Summary

- bip-0322.mediawiki
Explains why BIP322 exists, and what it changes. From feedback on Twitter.
Also adds a paragraph about when to return `ERROR`.
> BIP322: added background

- bip-0322.mediawiki
Test vector sighash was described as "sha256d(message)" but it is "sha256d(scriptpubkey || message_magic || message)". Also some formatting changes. (Sorry, I realized this after re-reading the BIP post-merge of last PR)
> bip322: fix test-vectors

- bip-0069.mediawiki
Found two "word repetition" mistakes in the BIP.
* changes modifies -> modifies
* index of of -> index of
> [Trivial] BIP69: Fix word repetition

- .travis.yml
- scripts/link-format-chk.sh
Several BIPs have mistaken links in format [ text ] ( url ) which this travis check will detect and complain about.
> travis: add a check for common mistake mediawiki links

- bip-0197.mediawiki
Since Seizable Collateral script have condition that can be refund by the borrower after the Seizure Period, Therefore, I think,  Seizable Collateral script is correct that the borrower can refund in Refund Period.
> [BIP197] Fix description of Refund Period

- .travis.yml
- README.mediawiki
- bip-0103.mediawiki
Obviously it expired, but also see comment here: https://github.com/bitcoin/bips/pull/504#issuecomment-540776823
> BIP 103: Mark as withdrawn

- bip-0045.mediawiki
Existing doc uses \`\` around code. Proper format calls for `<code>` tags.
> BIP-0045 - Formatting use <code> tags

- bip-0158.mediawiki
Fixes #779. This is a render issue in `<ref>` tag (c.f. https://en.bitcoin.it/w/index.php?title=BIP_0158&oldid=66816#Contents, This syntax error causes the rendering on GitHub to fail: https://github.com/bitcoin/bips/blob/b1b248fc6ade930c4c716eb9fed1b48be6796356/bip-0158.mediawiki#GolombCoded_Set_MultiMatch)
Fixes #783 
Fixes #799
> BIP 158: Fix mediawiki syntax typo, Remove remnants of the second filter type

- bip-0174.mediawiki
This PR specifies 2 new types and clarifies multi-byte types as was discussed on the mailing list a few months ago.
A version type of `0xFB` is added in the event that there is a breaking change to PSBT.
A proprietary type of `0xFC` is added to allow for proprietary use types for use in private. This type is followed by an identifier string and then a vendor defined subtype.
Lastly, multi-byte types are clarified. Types are redefined to be minimally encoded compact size unsigned integers so they can be variable length now if we happen to run out of one byte types somehow.
> Bip174 extensions

- bip-0174.mediawiki
The sentence seems to suggest that the "master key fingerprint" can be the fingerprint of any intermediate node on the derivation path, which isn't true.
> BIP174: Remove misleading sentence

- bip-0157.mediawiki
In this commit, we effectively revert #699 by allow clients to request
filter for up to 1k consecutive blocks. Testing in the field has shown
that applications are able to reduce perceived latency from syncing to
full functionality after an app has been offline for several days by
batching requests for filters. A value of 100 would mean each additional
day behind adds an additional round trip, resulting in 10s of
seconds of lag after just a few days of being offline. A value of ~1k
allows implementations to catch up with roughly a week's worth of
filters in a single round trip.
> BIP-0157: increase max getcfilters request to 1k blocks

- README.mediawiki
- bip-0325.mediawiki
This BIP describes Signet, a proposed new network for testing purposes.
> BIP 325: Signet

- README.mediawiki
- bip-0179.mediawiki
This was discussed [here](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2019-October/017369.html) and got really good feedback.
This is the BIP draft for it.
Feedback appreciated.
> BIP 179: Name for payment recipient identifiers

- bip-0174.mediawiki
As the key type is now defined as compact size integer, `At the beginning of each key is a compact size unsigned integer representing the type`, the comment in the first table in the document, about first byte of the key being the key type is no longer accurate.
As the structure of the key data is described further in the text after the table, and the comment that it starts with the compact size integer seems a bit long to be in that table, I think it is better to just remove the comment about the key data structure from the table, and leave the explanation to the text after the table.
> BIP174: remove 'first byte is the type' comment for key data

- bip-0174.mediawiki
About BIP-174, `PSBT_GLOBAL_PROPRIETARY`, `PSBT_INPUT_PROPRIETARY`, `PSBT_OUTPUT_PROPRIETARY` key description is incorrectly described as Version Number, so it fix to Proprietary Use Type.
> BIP174: Fix wrong description about Proprietary Use Type

- bip-0174.mediawiki
PSBT_INPUT_PROPRIETARY -> PSBT_IN_PROPRIETARY
PSBT_OUTPUT_PROPRIETARY -> PSBT_OUT_PROPRIETARY
to be consistent with other in/out type names that use shortened `IN` and `OUT`
> BIP-174: add missing types to Appendix A; fix proprietary type names

- bip-0174.mediawiki
This can be confusing where someone could think the separator separates the pairs and not the maps.
> BIP 174: Specify that separator only appears at end of the map

- bip-0119.mediawiki
One of the links is a 404: https://github.com/jeremyrubin/lazuli]
And the string "youtu.be" is blacklisted (for unknown reason!?) by default mediawiki installations.
This commit fixes those issues and changes all links to use the same syntax.
> Fix links in bip-0119.mediawiki

- bip-0039.mediawiki
Follow up to #883 
Advantages:
- 100% test coverage + [CI](https://github.com/aerosol/mnemo/actions) set up
- smaller tests that strictly address properties of the specs
- documentation
- [vectors.json](https://github.com/aerosol/mnemo/blob/master/priv/vectors.json) identical to [Trezor's](https://github.com/trezor/python-mnemonic/blob/master/vectors.json) + tests for seed verification with a passphrase
- idiomatic code, no compilation warnings, no unnecessary conversions to strings containing binary numbers
- flexible interface, e.g. works with raw binaries as well as hex-encoded
- does not output 1.5M of text when running tests
- does not confuse entropy with a private key
- no commented out code
- descriptive commit log
@prusnak let me know if you'd like me to squash the commits
> Replace elixir bip39 implementation

- README.mediawiki
- bip-0036.mediawiki
According to expiration rules, this does not need consent,
since it has expired.
> Reject BIP-0036

- bip-0039.mediawiki
The currently listed Rust implementation of BIP 39 doesn't pass the reference implementation's test vectors.
See --> https://github.com/infincia/bip39-rs/issues/21
> BIP 39: Update Rust implementation

- README.mediawiki
- bip-0043.mediawiki
Widely in use and used by BIPs 44, 45, 47, 49, 80, 81, 84, and 175 according to [luke-jr](https://github.com/bitcoin/bips/pull/912#issuecomment-621894238)
@prusnak @slush0 Please acknowledge.
> Mark BIP-0043 as final

- README.mediawiki
- bip-0099.mediawiki
The hard/soft-fork terminology, while widely used, is not clear cut, and given that this has not advanced, it would be best to reject this per BIP-0002 expiration rules.
@jtimon
> Reject BIP-0099 (expired)

- README.mediawiki
- bip-0104.mediawiki
- bip-0105.mediawiki
- bip-0106.mediawiki
- bip-0107.mediawiki
These BIPs all suggest changing the block size, they did not get consensus, they did not get a fork, they expired and are now only historically relevant. Marking them as expired per BIP-0002 expiration rules.
> Reject expired block size BIPs

- bip-0039.mediawiki
Add one more swift library to generate mnemonics (with multi lang support)
Here is an implementation:
https://github.com/matter-labs/web3swift/blob/e36e767eb2de26decb0c157aeef2d023a1175076/Sources/web3swift/KeystoreManager/BIP39.swift#L72
> BIP 39: Аdd swift library with multi lang support

- bip-0341.mediawiki
As discussed [on the mailing list](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2020-April/017801.html).
> bip-341: Commit to all scriptPubKeys in SigMsg

- bip-0174.mediawiki
While the Transaction Extractor section calls out the 0x05 Finalized scriptSig and 0x06 Finalized scriptWitness, this wasn’t as clear in the Input Finalizer section.
> BIP174: Input Finalizer finalized fields clarifications

- bip-0325.mediawiki
This changes the block signing algorithm for signet to be based on tx validation instead of a custom method. In particular, this allows the generalises the scheme so that new signets can make use of new signature/scripting methods (such as schnorr or musig) when they are added.
Note: this is incompatible with existing signets and requires a chain restart.
> bip-325: change signature scheme to be tx-based

- bip-0008.mediawiki
I'm pretty sure this is what makes sense and what the reference implementation does.
> BIP8: Fix pseudocode starting 1 block early

- bip-0032.mediawiki
~~This links to a (basic) Python3 implementation which passes all the bip's test vectors.~~
~~There are already two links to Python implementations but both are using Python2,
which was EOL at the begining of the year.~~
https://github.com/bitcoin/bips/pull/962#issuecomment-668274236
> bip-0032: remove the 'Implementations' section

- bip-0079.mediawiki
Bip78 now replaces bip79. https://github.com/bitcoin/bips/pull/923#issuecomment-634928082
@RHavar
> Update bip79 status

- bip-0174.mediawiki
These fields are needed to solve miniscripts, which may have hash preimage challenges.
See https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2019-March/016720.html for some earlier (very short) discussion.
> BIP174: add hash preimage fields to inputs

- bip-0174.mediawiki
Replaced `<tt>` with `</tt>` that fixes the rendering of the current BIP174. 
Fixes all symbols `&#123;` to be displayed correctly.
> BIP 174: Fix formatting changes

- bip-0342.mediawiki
Felt this could be under-defined as-is, and if this is wrong, would be nice to have correct text in its place to clear up the confusion
@sipa
> BIP 342: be slightly more explicit about codesep_pos

- bip-0325.mediawiki
While `OP_TRUE` challenges have been implicitly accepted until now, it was never defined exactly how these should be solved. This adds an exception for the case where the challenge is `OP_TRUE`, that the solution must be *absent*. I.e. not even an empty signet commitment may be present, or the block should be considered invalid.
Pros: this means a signet node with challenge `OP_TRUE` works *exactly the same* as testnet/mainnet, in terms of block generation (i.e. `generate*` RPC functions in Bitcoin Core can be used out of the box).
> bip-0325: clarify the OP_TRUE challenge special case

- bip-0325.mediawiki
For 4-byte-push case, the push opcode was not counted; the length element is 1-5 bytes, not 4.
Also tweaks the 'signet header' name (removing 'scriptSig').
> BIP 325: correct byte count for compact size

- bip-0155.mediawiki
* Increase the maximum length of an address from 32 to 512 bytes and 
clarify that the entire message should be rejected if it contains
a longer address.
(from https://github.com/bitcoin/bips/pull/766#issuecomment-519248699)
* Remove a contradiction about unknown address types - "MUST ignore" VS
"MAY store and gossip".
* Recommend gossiping addresses for unknown network ID and for networks
to which the node is not currently connected to. 
(from https://github.com/bitcoin/bips/pull/766#issuecomment-545067608)
* Clarify that the entire message should be rejected if it contains an
address with unexpected size (e.g. IPv4 address with length 5).
> BIP155: include changes from followup discussions

- bip-0155.mediawiki
* Clarify that by `VARINT` (variable integer) we mean [`CompactSize`](https://en.bitcoin.it/wiki/Protocol_documentation#Variable_length_integer), not `VARINT` (as in the source code) (huh!?). Relevant IRC discussion: http://www.erisian.com.au/bitcoin-core-dev/log-2020-07-27.html#l-94
* Change `time` to fixed 32 bits as that will work until year 2106, not just 2038 and takes 1 byte less than a variable integer format.
> BIP155: clarify variable integer format and change time to fixed 32 bit

- README.mediawiki
- bip-0114.mediawiki
This BIP by @jl2012 has been superseded by Taproot, I believe. I am not affiliated with this BIP, but I can request its rejection per BIP-0002 rules, since three years have passed since the last progress.
> Reject 114 (expired)

- bip-0174.mediawiki
[Bitcoin Core uses "roles" instead of "responsibilities"](https://github.com/bitcoin/bitcoin/blob/master/src/psbt.h#L559) and it makes semantical sense (plus less verbose).
> BIP 174: rename responsibilities->roles to match Bitcoin Core

- bip-0325.mediawiki
Strictly speaking the bip isn't wrong. It just happens that an empty byte vector is serialized identical to an empty vector of any other type, but it takes the reader an extra step. Thus, the minor fixup suggestion.
> BIP 325: Clarify that scriptWitness is a stack, not a byte string

- bip-0174.mediawiki
As observed in https://github.com/bitcoin/bips/pull/955 input fields should have `_IN_` in their names.
> BIP174: add `_IN_` to names of new hash preimage fields

- bip-0325.mediawiki
"either" and "Signet scriptSig header" seem to make no sense here, if other touchups are disagreeable I can drop them.
> Slight cleanup of signet commitment description

- bip-0155.mediawiki
It seems better to clarify that `CHECKSUM` in Tor onion v3 address uses SHA3-256 hash function.
> BIP155: Mention SHA3-256 explicitly

- bip-0325.mediawiki
In https://github.com/bitcoin/bips/pull/1003#discussion_r499466365 (where I adopt the approach here), it is pointed out that the message signature going into the scriptPubKey of the spending transaction is weird.
It should go into the scriptSig and/or scriptWitness, and the scriptPubKey for the spending tx is OP_RETURN.
> bip-325: correct placement of challenge

- bip-0008.mediawiki
When lockinontimeout is true, we don't transition directly from STARTED
to LOCKED_IN, so don't imply that we do.
If startheight or timeoutheight are not on a retarget boundary, they
behave as if they had been rounded up to the next retarget boundary,
so to keep things simple, require them to be at a boundary.
If timeoutheight is less than two retarget periods later than startheight,
behaviour when lockinontimeout is true (one retarget period of STARTED,
one of MUST_SIGNAL, one of LOCKED_IN, then ACTIVE) will not match
behaviour when lockinontimeout is false (one retarget period of STARTED,
then either LOCKED_IN or FAILED), so disallow that as well.
> BIP8: clarify timeoutheight behaviour and requirements

- bip-0155.mediawiki
Mandate to send `sendaddrv2` to the peer before sending our `verack`
to them.
This way we know that the peer does not support `addrv2` if we did not
receive `sendaddrv2` from them before receiving their `verack`.
> BIP155: change when sendaddrv2 is to be sent

- bip-0008.mediawiki
With the addition of the MUST_SIGNAL phase, signalling during LOCKED_IN is no longer needed for activation coordination, so drop it.
> BIP8: Make signalling during LOCKED_IN recommended rather than mandatory

- bip-0008.mediawiki
Based on #1020 since they touch neighbouring lines in the BIP.
Using the same threshold for MUST_SIGNAL as STARTED means that any chain
that would have resulted in activation with lockinontimeout=false will
also result in activation with lockinontimeout=true (and vice-versa).
This reduces the ways in which a consensus split can occur, and avoids
a way in which miners could attempt to discourage users from setting
lockinontimeout=true.
> BIP8: allow some MUST_SIGNAL blocks to not signal

- bip-0340.mediawiki
The terms "public/private nonce" are used in the Adaptor Signatures explanation without definition.
> Mention that public nonce is ''R'' and private nonce is ''s''

- bip-0085.mediawiki
I've noticed a small typo in the specification of bip 85 -- hardened derivation was after the slash.
> BIP-0085: fix typo

- bip-0039.mediawiki
Add a paragraph which explains that using a non-English bip39 mnemonic is usually a bad idea.
> bip39: discourage from using localized wordlists

- bip-0141.mediawiki
This makes the behaviour of the reference implementation clear for this computation, which was implied by the previous sentence but not explicited in the next one.
> bip-0141: clarify the sigop count calculation for CHECKMULTISIG

- bip-0174.mediawiki
The current version of the spec requires creator role to initialize empty input fields, but says nothing about output field initialization. At the same time, the following role, updater, "should also add redeemScripts, witnessScripts, and BIP 32 derivation paths to the input and output data if it knows them.", which does not make any sense if the fields were uninitialized. The [current Bitcoin Core implementation does this](https://github.com/bitcoin/bitcoin/blob/a24806c25d7a81a9c436de58eb5778d93abab16b/src/psbt.cpp#L12), and [other PSBT implementations, like rust-bitcoin, follow this practice](https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/util/psbt/mod.rs#L59)
> BIP 174: require creator to initialize empty output fields

- README.mediawiki
- bip-0175.mediawiki
Following @ysangkok proposal a few months back here https://github.com/bitcoin/bips/pull/960
I propose to reject this BIP due to lack of meeting the BIP process requirements.
Main point that has not been addressed as part of this protocol is the data management aspect, Greg pointed this point in the bitcoin mailing list.. I highly recommend refraining from using this protocol, I would suggest to migrate to other protocols that handle this aspect.
Regards,
Omar
> Reject BIP175

- bip-0322.mediawiki
Changes the validation rules to always require (script) standardness checks, except for checking NOPs and version numbers, where incorrect values result in "inconclusive" rather than "invalid". Allow validators to also return "inconclusive" when they encounter a script that they're unable to interpret.
This makes it possible to write a BIP-322 validator using Miniscript, and to write (say) a p2pkwh-only validator while remaining within spec. Both should encourage adoption.
Also removed the `to_spend` transaction from the wire serialization because it is a pure function of the address and message.
Mailing list discussion: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2020-December/thread.html
> bip322: (another) significant overhaul

- bip-0034.mediawiki
Non minimal encodings are rejected by the bitcoin-core client because it only checks against a specific encoding.
Link for reference: https://github.com/bitcoin/bitcoin/blob/master/src/validation.cpp#L3503
For example:
Height 16512 has two encodings which should be valid according to the spec. 03804000 and 028040. However, the prior would always be rejected due to the implementation of the BIP34 height check.
> BIP34 encoding clarification

- bip-0008.mediawiki
Simplify the validity check that at least threshold blocks are signalling during the MUST_SIGNAL phase for BIP 8.
> bip 8: simplify MUST_SIGNAL check

- bip-0350.mediawiki
This just updates broken URLs.
@sipa
> bip-0350: fix links for reference implementations

- bip-disable-tx.mediawiki
This message, valid between version/verack for peers with version >= 70017,
would allow establishing at the time of connection that no transactions will be
announced/requested between those peers.
> Add BIP 338: Disable transaction relay message

- bip-0125.mediawiki
+ Change 'Client support' section to 'Backwards compatibility'
+ Reasons: avoid confusion and according to the format mentioned in the below link:
https://github.com/bitcoin/bips/blob/master/bip-0002.mediawiki#specification
+ Discussed changes in https://github.com/bitcoin/bips/pull/994
> BIP 125: Change 'Client support' to 'Backwards compatibility'

- bip-0174.mediawiki
Simple Signer Algorithm was lacking an index argument (last one) on all function calls
> Fixing Simple Signer Algorithm

- bip-0118.mediawiki
As per my understanding, the value is committed in the signature(sighash msg) and is not being supplied as an additional witness
> Change `witness` to signature

- bip-0085.mediawiki
- Added Ian Coleman's Mnemonic Code Converter to the "Other Implementations" section
- https://iancoleman.io/bip39/ is a nice tool to play around with and to derive test data for BIP-85
PS: Sorry that I did not include this in the previous PR #1083. I just found this this very moment, but I think it is worth while to include because it gives the user/reader an instant tool to play with and to see results of BIP-85.
> BIP-85: Added Ian Coleman's Mnemonic Code Converter

- bip-0341.mediawiki
- bip-0342.mediawiki
Also remove mention of non-existing examples.
Test vectors and examples could get more love, but at least this points implementers to the existing test vectors.
> BIP 341/342: Add link to Bitcoin Core test vectors

- bip-0341.mediawiki
- bip-0342.mediawiki
Adds mainnet and testnet3 activation parameters. This uses the "speedy trial" approach [0]  with some refinements to the exact mechanism [1], as implemented in bitcoin/bitcoin#21377 . Parameters are selected based on previous discussions [2] [3] [4]. The parameters are:
* starttime = 2021-04-24 00:00 UTC
* timeout = 2021-08-11 00:00 UTC
* min_activation_height = 709632 (est mid November 2021, mainnet only)
* threshold = 1815 / 2016 blocks (90%, mainnet only)
In terms of block heights, that will likely mean the first signalling period for mainnet should start at height 681408, approximately April 29th UTC, and will likely mean signalling will continue for 8 retarget periods until height 697536 (which if blocks arrived at 10 minute intervals, would be due around 2021-08-20).
[0] …
> BIP341: speedy trial activation parameters

- README.mediawiki
- bip-0088.mediawiki
- bip-path-templates.mediawiki
Was first announced in https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2020-July/018024.html
Motivation and descriptions of usecases are given in the BIP draft, in the mailing-list post, and expanded in the replies to this mailing-list post and in [Bitcoin Optech newsletter 105](https://bitcoinops.org/en/newsletters/2020/07/08/).
While this draft BIP did not receive extensive public discussions, it did not receive any rejections or criticism either. Within private or semi-private discussions, people said that they like the idea, noted the usefulness of this format and having it standardized. I attribute the lack of public discussions to the template format being boring but practical, and thus uncontroversial. I think that having this as a formal standard will be a benefit to the …
> BIP 88: Templates for Hierarchical Deterministic derivation paths

- README.mediawiki
- bip-0343.mediawiki
- bip-mandatory-activation.mediawiki
This PR specifies a BIP 8(LOT=true) deployment to activate Taproot. Mandatory signaling would attempt to be enforced in approximately November 2022 (defined by block height) assuming the signaling threshold is not met before then.
Original mailing list discussion: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018783.html
> BIP 343: Mandatory activation of taproot deployment

- bip-0136.mediawiki
BIP-350 introduces a modification to the checksum of the Bech32 specification from BIP-173. This new variant is referred to as Bech32m. 
This pull request updates all the txref test vectors with the new Bech32m checksums and also adds several new examples and clarification of the existing text.
> BIP-0136: updates data encoding/decoding examples due to bech32m/bech32

- bip-0032.mediawiki
- bip-0039.mediawiki
- bip-0085.mediawiki
I would like to add my HD (paper) wallet implementation to BIP{32,39,85}. It is written as a follow up to reading @jimmysong great book - Programming Bitcoin. 
I had some issues trying to figure out what is going on just by looking on some other python implementations so I decided to write my own as a part of learning process. It should be easy to read and has a heavy load of unit tests. I hope it will help some novice bitcoiners to make their learning curve less steep.
> added 'btc_hd_wallet' amongst implementations in bip32, bip39, bip85

- bip-0002.mediawiki
Update language to clarify that there are multiple editors.
> Add Kalle Alm as BIP editor

- bip-0021.mediawiki
Text mentions `size` param and provides broken link to the explanation which is absent. It seems the parameter was removed after strict requirement to always use bitcoin denomination, but this line was left.
> Removing size param (not used anymore)

- bip-0032.mediawiki
As mentioned in https://github.com/bitpay/bitcore-lib/issues/47, https://github.com/iancoleman/bip39/issues/58 and https://github.com/btcsuite/btcutil/issues/172, the private key with leading zeros(i.e. less than 32 bytes) should be padded to 32 bytes when we derive a hardened child private key from a private key.
Unfortunately, the original test vector 3 is not suitable for this case since both keys are 32 bytes.
In the new test vectors, the key m/0<sub>H</sub> is 31 bytes.
[btcsuite/btcutil](https://github.com/btcsuite/btcutil) just fix the bug. See https://github.com/btcsuite/btcutil/pull/182.
> BIP32: Modified test vectors for hardened derivation with leading zeros

- bip-0009.mediawiki
Do two minor fixes to BIP-0009
- Add a couple of extra hyperlinks to other bip docs to assist the reader
- Fix typo, remove unneeded 'in'
> Minor fixes to BIP-0009

- bip-0088.mediawiki
The text describing the example wrongfully stated "followed by any non-hardened index" while the second index is just 0
> BIP88: fix description of the "*h/0" example

- bip-0174.mediawiki
The description of `keytype` incorrectly said it had to be unique: it's the whole `key` that must be unique, not the `keytype` (since we can for instance have multiple `xpubs` in the global map).
@achow101
> BIP 174: clarify key uniqueness

- bip-0341.mediawiki
It is [0] but the pubkey is index [1]
> BIP 341: fix tuple index in taproot_tweak_pubkey

- bip-0173.mediawiki
When describing the segwit address, `bc1q...` for example - the `q` represents witness version `0` but it is not one entire byte as the BIP currently describes it, it is one bech32 character which only represents 5 bits.
(unless the intention is to describe the byte in terms of how ASCII characters occupy one byte?)
> BIP173: segwit address witness version is one 5-bit char not one byte

- bip-0155.mediawiki
BIP155: extra-clarify the semantic of sendaddrv2.
This is also how the code works currently.
There seems to be some [misinterpretation](https://github.com/bitcoin/bitcoin/pull/22245#issuecomment-862246086) of the current wording in BIP155. Clarify that (hopefully).
> BIP155: extra-clarify the semantic of sendaddrv2

- bip-0341.mediawiki
Segwit version 1 is encoded by Bech32m given by BIP350
> Replaces Bech32 by Bech32m in BIP341

- bip-0032.mediawiki
This sentence should use a singular 'key' instead of 'keys'. Change
'knowing an extended public keys allows' to be 'knowing an extended
public key allows'
> Remove typo: plural

- README.mediawiki
- bip-0086.mediawiki
This BIP specifies a suggested derivation path to use for single key P2TR outputs, following BIP 43/44.
Test vectors and the actual derivation path value for the purpose will be set after receiving a BIP number.
> BIP 86: Key Derivation for Single Key P2TR Outputs

- bip-0039.mediawiki
Old repo is archived and links to the new repo are found in the old one's README file. This change updates the old repo's link to the new one.
> Updated URL of the JavaScript reference implementation

- README.mediawiki
- bip-0118.mediawiki
Lots of updates to BIP 118 in light of taproot. cc @cdecker
> Update BIP 118 for taproot, rename to ANYPREVOUT

- bip-0118.mediawiki
The key version should be 1 unless I am misunderstanding something.
> BIP118: Key version should be 0x01

- bip-0341.mediawiki
Functions defined in the document refers to `reference.py` created in BIP340 and there the `lift_x` function accepts bytes and converts to int internally https://github.com/bitcoin/bips/blob/99701f68a88ce33b2d0838eb84e115cef505b4c2/bip-0340/reference.py#L71
> remove int_from_bytes in lift_x call since it is done internally

- bip-0174.mediawiki
The link to PSBT2, which was broken before the BIP number was assigned, is now linked to BIP370.
> [BIP174] Fix broken link to psbt2

- bip-0048.mediawiki
Plural "wallets", not possessive "wallet's".
> BIP-48: Trivial errant apostrophe fix

- bip-0078.mediawiki
Non-Witness: 
Outpoint size = 32+4
Sequence size = 4
ScriptSig VarInt Size= 1
Witness: 
WitScript VarInt Size= 1
Then script itself: 65 signature size + 1 byte of push opcode
`(32 + 4 + 4 + 1) + (65+1+1)/4=57.75`, rounded up `58`.
We assume 65 of signature size rather than 64, since we can't assume the sighash to be `Default`.
> [BIP78] Recommended fee rate estimation for P2TR

- bip-0043.mediawiki
@slush0 @prusnak 
cc @Arachnid
> BIP 43: Reserve purpose codes 10001-19999 for SLIPs

- README.mediawiki
- bip-0380.mediawiki
- bip-0381.mediawiki
- bip-0382.mediawiki
- bip-0383.mediawiki
- bip-0384.mediawiki
- bip-0385.mediawiki
- bip-0386.mediawiki
Here are several BIPs specifying output script descriptors as implemented in Bitcoin Core.
In order to make it easier for implementors to indicate which descriptors they support, I've split up the specifications into multiple BIPs. The first is a general BIP describing the philosophy, general structure, shared expressions, and the checksum. The rest of the BIPs specify each descriptor function itself and are grouped into categories of non-segwit (pk, pkh, p2sh), segwit (wpkh, wsh), multi (multi, sortedmulti), combo (by itself), opaque wrappers (raw, addr), and tr (by itself).
> [BIPs 380-386] Output Script Descriptors

- bip-0119.mediawiki
Opening for bikeshedding here before mirroring the code changes.
Some folks found StandardTemplateHash being a consensus definition and not a policy definition confusing.
This PR attempts at unambiguous names. More verbose than I like, but it's readable at least.
Bikeshed now or forever hold your peace :laughing:
> Update BIP-119 Variable Names

- bip-0078.mediawiki
There was a bug in the payjoin client reference implementation if the receiver used output substitution, causing the payjoin to fallback to normal payment unecessarily.
Fixing bug reported by @Kixunil (https://github.com/btcpayserver/btcpayserver/issues/2677)
Fixed on the C# client (https://github.com/btcpayserver/BTCPayServer.BIP78/commit/451e1126f7b3f5c6bb9b648aa3ac6bd7485996ee) and tested by Kixunil.
The bug was best explained by @Kixunil
-------
* The code was iterating over proposed PSBT outputs and have original outputs in a queue.
* It was comparing the proposed output to the output at the front of the queue
* If there are two outputs: payee, payer_change - in this order, then if payee substituted the output, the comparison is false. Then  we did nothing with it and thus leaving …
> [BIP78] Fix client implementation when there is output substitution

- bip-0158.mediawiki
This sentence is grammatically incorrect:
"Empirical analysis also shows that was chosen as these parameters ..."
Elect to fix the sentence to be:
"Empirical analysis also shows that these parameters ..."
> [BIP 158] Fix grammar - remove 'was chosen as'

- bip-0078.mediawiki
This is a transaction with inputs of type P2SH-P2WPKH 
1. P2SH-P2WPKH is defined as a valid type for payjoins in this doc and the other type not.
2. The RedeemScript(0 c78a45725355828d5658074dd5260d5fcb698530) consists of 0 + <20 bytes> and indicates therefore P2WPKH-Type. https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#P2WPKH_nested_in_BIP16_P2SH
> typo in bip-0078

- bip-0370.mediawiki
Replacing occurences of PSBT_GLOBAL_PREFERRED_LOCKTIME with PSBT_GLOBAL_FALLBACK_LOCKTIME to match the name in the global map table.
> BIP 370: Use PSBT_GLOBAL_FALLBACK_LOCKTIME in text

- bip-0174.mediawiki
This is a clarification on how PSBT_IN_FINAL_SCRIPTSIG and PSBT_IN_FINAL_SCRIPTWITNESS should be handled when the data is empty. Based on feedback from @achow101 on twitter https://twitter.com/kallerosenbaum/status/1443856371368271872
It seems [more people than I](https://twitter.com/benthecarman/status/1443858125971501057?s=20) had interpreted the bip like you should always set PSBT_IN_FINAL_* even if data is empty, but @achow101 says we should leave those unset.
> BIP 0174: Clarify use of PSBT_IN_FINAL_* when data is empty

- bip-0119.mediawiki
This PR contains some minor updates to BIP-119 that clarify
1) Deployment params
2) CTV v.s. Anyprevout
3) Synergies with other softforks
4) The choice of SHA-256 v.s. RIPEMD
5) The choice of Untagged hash vs tagged
> Minor Updates to BIP-119

- bip-0157.mediawiki
This sentence does not quite make sense
... the size of a `cfcheckpt` message is not drastically from a `cfheaders` between two checkpoints. ...
Change it to be:
... the size of a `cfcheckpt` message is not drastically different from a `cfheaders` message between two checkpoints. ...
> [BIP 157] Add missing words to sentence

- bip-0341.mediawiki
- bip-0342.mediawiki
These clarifications would each have prevented an error in our initial implementation of these BIPs.
> BIP341/342: Implementation clarifications

- bip-0341.mediawiki
- bip-0341/wallet-test-vectors.json
This adds a set of wallet-focused BIP341 test vectors covering:
* scriptPubKey computation (from internal key & script tree)
* control block construction (for script path spending)
* key path spending (sighash computation / deterministic signing)
It is primarily aimed at constructions that are useful right now, and excludes for example signing with annex for that reason. BIP342 semantics are not covered directly, as the scope of that is extremely wide, but control block computation is, plus most of sighash computation is shared with BIP341 key path spending.
These test vectors are generated through a scenario in https://github.com/bitcoin/bitcoin/pull/23394, where an actual (regtest) chain is constructed and validated containing the relevant transactions, and also implemented there …
> BIP341 test vectors

- bip-0341.mediawiki
While this change isn't needed, I think it is nice for the reader to tell if and when the deployment activated.
ping @sipa, @jonasnick, @ajtowns for ACK or NACK
> Mention activation heights in BIP 341 🥕

- bip-0119.mediawiki
Adds pseudocode definition of `CheckDefaultCheckTemplateVerifyHash()` to BIP-119 specification in the obvious way. Even though it is trivial, it should be included to dissolve any doubts.
> Define BIP-119 CheckDefaultCheckTemplateVerifyHash

- bip-0032.mediawiki
It's not possible for `I_L` to be zero, since `I_L` is a binary blob. It is possible for `parse_256(I_L)` to be zero, since `parse_256(I_L)` is an integer. `parse_256(I_L) = 0` is also an error condition in other parts of the document.
> Fix typo in BIP 32

- bip-0038.mediawiki
This does not change the content of the BIP, but makes things clearer to people reading the BIP in today's context (where there are multiple "bitcoin address" types that use compressed DER public keys, and taproot introduces another compressed format (x-only public keys))
These additions to the language are implied given the late-2013 early-2014 context of this BIP. This fix will make them explicit.
> Clearer language in BIP38

- bip-0174.mediawiki
`PSBT_OUT_TAP_LEAF_SCRIPT` seemed to appear in output key sections by copy-paste from input section. First, it shares the same byte no as `PSBT_OUT_TAP_TREE`, second its description talks about "witness"
> BIP-174: Removing PSBT_OUT_TAP_LEAF_SCRIPT

- bip-0119.mediawiki
when drafting the BIP I attempted to triangulate what the width of the fields for number of inputs/outputs should be from various sources in the codebase, and made an error in looking at the signing and encoding logic, and not the _decoding_ logic which restricts vectors (vin, vout) to MAX_SIZE which is 33554432. This fully justifies not using a wider type (uint64_t).
Also clarified arguments for not using a narrower type (uint16_t) which would be possible just for the vIn based on block size, because it's a leaky abstraction (you can still encode and decode such a transaction,  just not mine it).
thanks to @roconnor-blockstream for pointing this out
> Fix BIP-119 Typo + Clarify the reasons for 32 bit lengths

- bip-0119.mediawiki
This was pointed out to be missing from the BIP by @petertodd.
CTV is, as implemented in the PR, safe. This is not by accident, CTV was designed to not have these problems. But it's important to make these DoS issues and CTV's design w.r.t. clear, especially since the adding of the example checker logic did make the BIP's spec dos-able (though not any reference implementation).
> [BIP-119] Add notes and warnings about DoS during validation of CTV.

- bip-0119.mediawiki
Pointed out by @roconnor-blockstream that it's more accurate to describe this limitation with respect to currently existing channels, and not Eltoo. Also renamed Channel Factories to "Batched Channel Creation" as channel factories refers to a specific protocol, where Batched Channel Creation is a more general term.
> [BIP-119] Rename Channel Factories / Clarify Malleability

- bip-0174.mediawiki
In discussing https://github.com/rust-bitcoin/rust-bitcoin/pull/669?notification_referrer_id=NT_kwDOAA2G-7EyNDgwMTU5NzIxOjg4NjUyMw#event-5861680619 it's clear that the PSBT spec is ambiguous with respect to what values should be parseable for PSBTs, this patch clears up the ambiguity.
------------
Personally, I feel that the better path is to allow NULLDUMMY here, as there could be some situations whereby satisfaction is NP-hard without some indicator of use a signature or not:
e.g., a contrived example (not saying you should do this) is
```
<0> toaltstack
<pk0> Checksig OP_IF FROMALTSTACK <V0> OP_ADD TOALTSTACK OP_ENDIF
<pk1> Checksig OP_IF FROMALTSTACK <V1> OP_ADD TOALTSTACK OP_ENDIF
...
<pkN> Checksig OP_IF FROMALTSTACK <VN> OP_ADD OP_ENDIF
<T> OP_EQUAL
```
where to satisfy requires …
> [BIP-174] Clarify that partial_sig should be a valid.

- bip-0322.mediawiki
This
* adds test vectors to the BIP-322 (signmessage) proposal (more needed, but better than nothing)
* clarifies how messages are serialized as this was slightly ambiguous
* clarifies that the <code>to_sign</code> transaction must have version, locktime, and sequence all set to 0 for the SIMPLE format (signature only)
> clarify message serialization and add test vectors to BIP-322

- README.mediawiki
- bip-0326.mediawiki
This adds a BIP for improve could the privacy of certain off-chain protocols like Lightning, CoinSwap or DLCs.
It has already been implemented by Sparrow wallet.
> BIP 326: Anti-fee-sniping protection with nSequence in taproot transactions to improve privacy for off-chain protocols

- bip-0338.mediawiki
Clarify that peers must set fRelay=false in order to send disabletx,
and that notfound and feefilter messages may not be sent.
> BIP338: Add further restrictions on disabletx

- bip-0119.mediawiki
Builds on #1294.
This cleans up the spec to be 'higher level' psedocode that may be easier as a reference to parse than the C++ dump from the reference implementation.
Also makes abundantly clear the anti-DoS requirements for validation, hopefully.
cc @achow101 @petertodd 
note: not that anyone *should* implement bitcoin in python...
> [BIP-119] Clean Up Spec of Opcode

- bip-0174/coinjoin-workflow.svg
- bip-0174/multisig-workflow.svg
This is basically the same as https://github.com/bitcoin/bips/pull/1184
and https://github.com/bitcoin/bips/pull/1192. In 1192, node connections
are visible, but with low contrast. In 1184 and in this case, arrows are
barely visible at all.
> BIP 0174: Remove transparent background from figures

- bip-0322.mediawiki
While attempting to implement bip322 I was unable to generate the same signature as the ones provided. Furthermore, I was unable to verify these signatures in my implementation. After some digging, I noticed the test vectors in the bip322 PR to Bitcoin Core uses different values.
See util_tests.cpp in https://github.com/bitcoin/bitcoin/pull/24058
This P.R. replaces the current test vectors with the ones from the P.R.
It also adds additional test vectors for the transaction hashes of the to_spend and to_sign transactions. Having these would have speeded up my debugging process significantly.
> Fix incorrect signature test vectors in BIP322

- bip-0119.mediawiki
@achow101 pointed out to me that mediawiki does in fact have syntax highlighting, and how I could use it in BIP-119.
This PR adds that as a clean up, as well as marginally improves comments.
> [BIP-119] Use mediawiki syntax highlighting, add comment to spec

- bip-0141.mediawiki
When describing the `witness` field, reword "witness data" to "witness field" as "witness data" refers also to the `marker` and `flag` fields.
https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#transaction-size-calculations
> Base transaction size is the size of the transaction serialised with the witness data stripped. 
Here, "witness data" refers to having the `marker`, `flag` and `witness` fields stripped.
https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#transaction-id
> The `witness` is a serialization of all witness data of the transaction.
However, here "witness data" refers to just the `witness` field.
> bip-141: improve `witness` field wording

- bip-0300.mediawiki
I have updated all instances of "ACK Value" and "ACK Counter Value" within the BIP to be "ACK-counter". 
Updates made to align with term used through out the BIP:
Line 213 - adding explicit mention of "ACK-counter"
Line 229 - adding explicit mention of "ACK-counter"
Line 257 - replaced "ACK-value" with "ACK-counter"
Line 288 - replaced "ACK value" with "ACK-counter"
> Update bip-0300.mediawiki with consistent use of "ACK-counter" term

- bip-0340.mediawiki
- bip-0340/reference.py
- bip-0341.mediawiki
As pointed out by @Randy808 [here](https://github.com/bitcoin/bips/pull/1348#issuecomment-1212973614).
> BIP 340 & 341: use consistent definition of lift_x

- README.mediawiki
- bip-0372.mediawiki
- bip-p2c.mediawiki
- scripts/buildtable.pl
A proposal was originally discussed in https://github.com/bitcoin/bips/pull/1239 and than on a mailing list https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-January/019761.html
> BIP 372: Pay-to-contract tweak fields for PSBT

- bip-0118.mediawiki
Don't try to directly duplicate BIP 341/342 as much, to hopefully make it easier to understand.
> BIP118: simplify explanation of signature message

- bip-0341.mediawiki
It seems like there are some missing type conversions in the example python code for `taproot_tweak_seckey`.
Changes made:
- Convert seckey0 to bytes at the start of the function. 
- Return the output as bytes for consistency with the rest of the code.
> BIP 341: add missing conversions between bytes and int

- bip-0070.mediawiki
Came across "broken" url. This should have given a 404, but there is actually a user `1237788`.
> [Trivial] BIP-70 Fixing sipa's gist proposal url

- bip-0011.mediawiki
- bip-0012.mediawiki
Replaced the current implementation URL which gives an error 404. The new link is to the equivalent branch since the original named branch has been removed.
> bip-0011/12 - fixed broken implementation url

- bip-0330.mediawiki
The reconciliation protocol assumes using one role consistently. Since it is irrelevant which one is which, we can imply that the initiator of the P2P connection will assume the role of reconciliation initiator.
This protocol simplification will seep into the implementation.
> BIP330: drop redundant booleans from the sendtxrcncl message

- bip-0341.mediawiki
`lift_x` returns `None` if the input integer is not an X coordinate on the curve to indicate failure. `point_add`, on the other hand, interprets `None` as the point at infinity. Therefore, without this commit, if the internal `pubkey` is not a valid X coordinate, the function will not fail, which contradicts the specification in the "Script validation rules section". Instead, it sets `Q` to `t*G`.
A test vector is being added here: https://github.com/bitcoin-core/qa-assets/pull/98
> BIP 341: Fix taproot_tweak_pubkey

- bip-0341.mediawiki
The `schnorr_sign` function from the [bip340 reference code](https://github.com/bitcoin/bips/blob/master/bip-0340/reference.py#L98) has a third required argument `aux_rand: bytes`.
Change:
- ~adding `aux_rand` as an optional argument that defaults to `0x0000...`~
- adding `bip340_aux_rand` as a required argument to the function `taproot_sign_key`
> BIP341: add aux_rand argument to taproot_sign_key

- bip-0341.mediawiki
In contrast to taproot_output_script, taproot_sign_key was not able to deal with
a script_tree that is None. This commit fixes taproot_sign_key such that it can
sign for such outputs.
This commit avoids changing the behavior of the functions except
taproot_sign_key at the cost of having some code duplication. Alternatively, one
could let taproot_tree_helper deal with a None script_tree directly.
> BIP 341: allow taproot_sign_key with no script tree

- bip-0174.mediawiki
- bip-0371.mediawiki
Clarify intended usage of PSBT_IN_TAP_BIP32_DERIVATION for key-spends.
> Update PSBT_IN_TAP_BIP32_DERIVATION key desc

- bip-0380.mediawiki
Parsers must handle checksum optionality, but applications can choose to reject descriptors that don't have a checksum.
> 380: Clarify optionality of descriptor checksum

- bip-0158.mediawiki
Currently the newline in list items in BIP-0158 is causing the text on the new line to be rendered as a code section. I am unsure why this is happening but putting all the text for each list item on a single line fixes it.
> Remove newline to fix list rendering

- README.mediawiki
- bip-0340.mediawiki
- bip-0341.mediawiki
- bip-0342.mediawiki
- bip-0343.mediawiki
Taproot is supported by Bitcoin Core and adopted by a majority of the network, so it should be marked as Final. The progression from Draft to Proposed and from Proposed to Final was likely forgotten.
> Mark Taproot BIPs as Final

- bip-0370.mediawiki
PSBTs with transaction version number less than 2 are valid for PSBTv0; therefore, mandating transaction version number 2 in a PSBTv2 implementation would create the situation where some valid PSBTv0 can't be converted to PSBTv2.
By only mandating the transaction version to be at least 2 when the transaction is modifiable (that is, when Creator and Constructor roles are distinct), the issue is avoided.
(h/t to @bucko13 for spotting the issue)
> PSBTv2: Relax transaction version requirement

- bip-0174.mediawiki
The Simple Signer Algorithm is not updated to the fact that SegWitv0 inputs are now typically expected to have both the non-witness-utxo and the witness-utxo field (instead of the ealier requirement of omitting the non-witness-utxo).
By reverting the order of the checks, it is at least semantically correct.
Possible TODOs for followups:
- Update for segwitv1 signing
- Recommend checking the non-witness-utxo for segwitv0 inputs.
> PSBTv0: Update Simple Signer Algorithm for SegWitv0 inputs

- bip-0341.mediawiki
Reading the spec closely the different language used for serialization of input outpoints and input amounts was confusing on first read. This change uses the same language for both, which makes it easier to read.
> Improve BIP-341 wording

- bip-0093.mediawiki
This adds two new test vectors, but otherwise purely corrects grammar/syntax mistakes and makes no changes to the BIP content.
> bip93: minor cleanups

- README.mediawiki
- bip-0084.mediawiki
Revisiting #1053, as this is now implemented by multiple software wallets and most hardware wallets (source: https://walletsrecovery.org).
@prusnak: You mentioned you didn't want to move this to Final as you'd like to expand it with Taproot handling, but I suppose that was abandoned in favor of BIP86?
> Mark BIP84 as Final

- bip-0329.mediawiki
Based on feedback received after BIP329 was initially published, this adds the following:
- An optional `origin` property containing key origin information which can be used to to disambiguate labels from different wallets contained in the same export
- A note on warning users if truncation is applied, along with a suggested maximum label length
> BIP329: Add optional key origin property and expand truncation note

- README.mediawiki
- bip-0350.mediawiki
Bitcoin Core and the network have been using it for years, so it should be marked as final.
> Mark bech32m as final

- bip-0329.mediawiki
This PR adds a `spendable` state to outputs in BIP 329, allowing wallets to properly export and import the spendable state of outputs.
This allows wallets to prevent users accidentally spending funds they previously marked as unspendable in wallets like Sparrow or Samourai that support coin control. 
We plan to implement the usage of BIP 329 into [Envoy](https://github.com/Foundation-Devices/envoy) shortly, and wanted to ensure that our users have a way to transfer spendable state in and out of the wallet and to other BIP 329-respecting wallets without issues, thus the PR.
Note: this does expand the scope of this BIP very slightly, almost making it a wallet "metadata" BIP instead of purely label-related. I'm happy to expand the PR accordingly by updating the title and copy to reflect that …
> BIP 329: Add `spendable` state to outputs

- README.mediawiki
- bip-0389.mediawiki
This was posted to the mailing list a couple of weeks ago.
> [New BIP 389] Multipath descriptors

- bip-0137.mediawiki
Fix a typo in BIP-317. Change "enterence" to "entrance.
> BIP-137: Fix typo

- bip-0039.mediawiki
Updated [bip-0039.mediawiki](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) to include a link to [anquii/BIP39](https://github.com/anquii/BIP39) in the Swift section of implementations.
> Add link to anquii/BIP39 (Swift)

- bip-0119.mediawiki
I'd like to propose that James O'Beirne be added as an author to BIP-119. James has done extensive research on covenants, including 119, and is actively involved in Bitcoin Development. Since I am no longer actively involved in Development, adding James as an author will give the the BIP an active steward for any changes required going forward.
> Add James O'Beirne to 119 Author List

- bip-0324.mediawiki
by merging it with the version packet. Or more accurately, by merging it with the first packet sent after garbage termination, which may be a decoy packet or the version packet.
The new protocol simplifies implementations:
- A protocol state machine won't need separate states for garbage authentication and version phases.
- The special case of "ignoring the ignore bit" is removed.
- The freedom to choose the contents of the garbage authentication packet is removed. This simplifies testing.
The reason for having a separate garbage authentication packet was to materialize the separation of the key exchange phase and version negotiation phase even in the bytestream on the wire. However, this is not necessary, and arguably, these phases are still properly separated: Since the AEAD will ensure …
> bip324: Remove garbage authentication packet (breaking change)

- bip-0002.mediawiki
BIP authors should be allowed to write their BIPs in Markdown. The MediaWiki syntax that GitHub uses appears to be entirely undocumented (it does not always match mediawiki's documentation) which makes writing complex BIPs rather difficult. Markdown is much simpler and more concise.
> bip 2: allow markdown

- bip-0380.mediawiki
Examples for invalid hardened indicators also have a too long fingerprint, which is confusing.
> BIP-380: correct fingerprint for invalid hardened indicators examples

- README.mediawiki
- bip-0043.mediawiki
- bip-0044.mediawiki
- bip-0049.mediawiki
- bip-0084.mediawiki
I just noticed inconsistency between BIPs dealing with the account structures:
- BIP-00{43,49,84} were Informational, while BIP-00{44,86} are Standards Track => this PR changes the former to the Standards Track too
- BIP-0044 was not marked as Final where BIP-00{43,49,84,86} are => let's mark BIP-0044 as Final too
> BIP-00{43,49,84}: move to Standards Track + BIP-0044: mark as Final

- bip-0119.mediawiki
Python requires a colon at the end of an if statement to denote the beginning of the block of code that will be executed if the condition is True. If the colon is omitted, a syntax error will occur, and the code will not run. Since the syntax error will prevent the code from running, it won't introduce any vulnerabilities by itself. However, it will cause the application to fail at the point where the code is parsed, which might expose other issues if error handling is not implemented properly.
> added colon at end of if statement - bip-0119.mediawiki

- bip-0143.mediawiki
In the example of BIP 143, the unit of coin output only 'No FindAndDelete' is described with satoshi. so  changed it to the value of BTC unit according to other examples.
```
scriptPubKey : 00209e1be07558ea5cc8e02ed1d80c0911048afad949affa36d5c3951e3159dbea19, value: 200000
```
change to
```
scriptPubKey : 00209e1be07558ea5cc8e02ed1d80c0911048afad949affa36d5c3951e3159dbea19, value: 0.00200000
```
> BIP 143: Unify coin unit

- bip-0141.mediawiki
This adds documentation to BIP141 about which 1 byte push op codes are valid for segwit. This is needed because `OP_1NEGATE` is a 1 byte push op code, but is NOT a valid 1 byte push op code for segwit. See the implementation here for why `OP_1NEGATE` is not valid: https://github.com/bitcoin/bitcoin/blob/14d01309bed59afb08651f2b701ff90371b15b20/src/script/script.cpp#L228
> Specify which 1 byte push op codes are valid

- bip-0158.mediawiki
Added test vector for block `1414221`. In particular this block has no output scripts other than `OP_RETURN`, and it's corresponding filter is `0x00`. Also updated the spec to clarify the same.
> bip158: update test vectors

- bip-0002.mediawiki
Please see https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-September/015065.html
> BIP 2: Allow editors to fix typos

- bip-0021.mediawiki
Although not an "Other Implementations" section, people have been using the "Libraries" subsection of the "Reference Implementations" section in the same way. Thus removing this subsection with the same rationale as #1576.
> 21: Remove other libraries from reference implementations

- bip-0173.mediawiki
This is a follow-up to https://github.com/bitcoin/bips/pull/945 to reduce the scope of BIP173 to native segwit v0.
I expect that you may have feedback about the phrasing, @sipa.
> Reduce scope of BIP173 to native segwit v0

- bip-0324/test_sage_decoding.py
Tiny fix correcting the order of commands, for `git checkout` one has to change into the repository directory first.
> bip-0324: fix git instruction order in test_sage_decoding.py

- scripts/buildtable.pl
Adds markdown `.md` files to `buildtable.pl` so that it builds and checks them too.
Since markdown allows html tags, the check for a `<pre>` tag is fine to leave in; all `.md` formatted bips will be required to have a preamble section like formatted in the same way as the mediawiki ones.
> buildtable.pl: Also check .md files

- bip-0158.mediawiki
The M parameter is used as the inverse of the false probability rate, so change its incorrect usage in two places.
> BIP-158: Fix description of M parameter

- bip-0322.mediawiki
Following [this discussion](https://github.com/bitcoin/bitcoin/pull/24058/files#r872561862), add another valid sig vector not to confuse developer. 
It has been misleading some developers, as they think their implementation is wrong even if it's right.
This test vector is also included in ongoing implementation of BIP322(PR is closed but seems like still in development [here](https://github.com/luke-jr/bitcoin/commit/f2f4637b16cd956e5923c05154a5eeaf1801ef45))
> bip-0322: add another valid sig vector not to confuse

- README.mediawiki
- bip-0353.mediawiki
User behavior has clearly indicated a strong demand for the resolution of human-readable names into payment instructions. This BIP defines a protocol to do so using only the DNS, providing for the ability to query such resolutions privately, while utilizing DNSSEC to provide compact and simple to verify proofs of mappings.
I'd like to hereby request a BIP number assignment. What is the current approach to do so - since the mailing list has died, is a post on delving bitcoin the appropriate place to publish BIP drafts?
> Add BIP 353: DNS Payment Instructions

- bip-0015.mediawiki
Originally I opened https://github.com/bitcoin/bips/pull/1611 when I spotted a broken hyperlink in https://github.com/bitcoin/bips/blob/master/bip-0015.mediawiki.  I suggested changing the hyperlink to https://github.com/klynastor/supervanitygen, but since an email sent to the BIP Champion at genjix@riseup.net bounced back as undeliverable ("550 5.1.1 : Recipient address rejected: User unknown"), [@murch](https://github.com/murchandamus/murchandamus) suggested just removing the hyperlink altogether rather than guess at what it should be set to.
I agree that no hyperlink is better than a broken one, so the existing hyperlink should be removed.
I am closing https://github.com/bitcoin/bips/pull/1611 and opening this new PR instead.
> Remove broken hyperlink to Vanitygen

- README.mediawiki
- bip-0174.mediawiki
- bip-0328.mediawiki
- bip-0373.mediawiki
- bip-0380.mediawiki
- bip-0390.mediawiki
This PR contains 3 proposed BIPs, the main contents of which were sent to the bitcoin-dev mailing list in October. There have been a few changes, notably the addition of a new BIP for the derivation methodology which was split from the descriptors BIP.
I've also changed the PSBT BIP to use 33 byte plain aggregate pubkeys rather than xonly.
> 328, 390, 373: BIPs for MuSig2 derivation, descriptors, and PSBT fields

- README.mediawiki
- bip-0338.mediawiki
The PR implementing this BIP was never merged into Bitcoin Core, in favor of an alternative approach.
> Move BIP 338 to Withdrawn

- README.mediawiki
- bip-0324.mediawiki
It is actively used on the P2P network.
> Mark BIP324 as final

- README.mediawiki
- bip-0150.mediawiki
Mark BIP150 as Deferred. More robust and private protocols have been drafted and need to be formalized into a BIP (see https://github.com/sipa/writeups/tree/ea9a3329fd33cc2c50e7ea65920e885d9caa454a/private-authentication-protocols for an example)
> BIP150: Deferred

- bip-0046.mediawiki
In BIP46, the witness in the address derivation section states `<signature> <pubkey>`, which is incorrect. It should say `<signature> <witnessScript>` as specified for P2WSH in [BIP141](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#user-content-P2WSH).
> BIP46 clarify witness

- bip-0327.mediawiki
- bip-0327/gen_vectors_helper.py
- bip-0327/reference.py
- bip-0327/vectors/sig_agg_vectors.json
I made some minor corrections, which I believe are beneficial. Please let me know if any of them are incorrect or need modification.
Changes:
1. An error test vector doesn’t specify the `InvalidContributionError` type
2. In *DeterministicSign*, use `GetXonlyPubkey` instead of `GetPubkey` (doesn’t exist)
3. The `key_agg_and_tweak` fn doesn’t specify the return type
4. In `partial_sig_verify_internal`, the pubkey arg type should be `PlainPk` rather than `bytes`
5. Remove unnecessary `enumerate()` calls
- I suspect this was initially used in debugging to find the failing test vector, and then it was forgotten.
6. In `test_sign_verify`, add an additional `assert` statement that checks if two pubnonces add up to the infinity aggnonce.
cc @jonasnick @real-or-random
> bip327: minor fixes

- README.mediawiki
- bip-0094.mediawiki
A written specification for Testnet 4 has been requested [in the PR discussion](https://github.com/bitcoin/bitcoin/pull/29775) and a BIP seems to be the right place for this.
Given the active discussion in the PR I think it's best if this is kept open until the PR is merged. I will keep it up-to-date and track the current status of the PR.
> BIP94 Testnet 4

- bip-0094.mediawiki
This aligns the BIP with the Bitcoin Core pull request and sets the allowed delta between the first block of the new difficulty period and the previous block to 7200 seconds (2 hours) instead of 600 seconds.
See also the discussion in the PR: https://github.com/bitcoin/bitcoin/pull/29775#discussion_r1704428831
> BIP94: Change timewarp delta to 7200 seconds

- bip-0388.mediawiki
One important aspect of wallet policies is how they help preventing pubkey reuse. I think it's worth explaining it in some detail in the motivation section.
Also adding links to BIP-379, and fixing a nit.
Strictly speaking, one might want to formally specify all the miniscript fragments in the grammar specification; however, that would require listing all the miniscript fragments, which doesn't seem useful. As the grammar for miniscript rules are somewhat obvious, I think a simple link to BIP-379 is more useful in practice.
> 388 - Add more motivation, and links to miniscript BIP

- bip-0174.mediawiki
- bip-0353.mediawiki
When using BIP 353 for on-chain addresses (incl silent payments),
it is useful to be able to include DNSSEC proof information in
outputs of a PSBT, which we enable here by defining a standard
field for it.
> Add a PSBT per-output field for BIP 353 DNSSEC Proofs

- bip-0353.mediawiki
If someone puts a lightning BOLT 12 offer in a BIP 353 entry with the offer expiring before the DNS entry's TTL (plus now), they may get stuck being unpayable, so its worth explicitly mentioning that people should take care here.
> Explicitly mention care around payment instruction expiry in 353

- README.mediawiki
- bip-0085.mediawiki
Revert bitcoin/bips#1600, as it contained a breaking change.
The desired changes from that pull can be proposed separately.
> Revert "BIP85: Clarify spec, correct test vectors, add Portuguese language code, add dice application"

- README.mediawiki
- bip-0119.mediawiki
I discussed removal with @jamesob at the beginning of the summer, as his focus is elsewhere these days. Original context on his addition is here https://github.com/bitcoin/bips/pull/1482.
Since the BIP editor community is more active these days, I'd like to see the addition of an editors/champion/draft-team metadata, and would love to add a volunteer or two to the BIP should it need any edits for that role.
> BIP119: remove James O'Beirne as co-author

- README.mediawiki
- bip-0327.mediawiki
Following the merge of https://github.com/bitcoin-core/secp256k1/pull/1479, it looks like the status of BIP327 "MuSig2 for BIP340-compatible Multi-Signatures" can be updated from Draft to Active.
> BIP327: update status from Draft to Active

- bip-0300.mediawiki
this section is (rightly) commented out, but it still (wrongly) shows up at the table of contents in the beginning, this should fix it
> BIP300: fix up markup in comment header

- bip-0099.mediawiki
This extra space appears to unintentionally trigger the markup rules for preformatted text.
> Fix BIP-99 Formatting

- bip-0002.mediawiki
Only change is `s/http/https/` for these URLs.
> BIP2: replace legacy http links with https

- README.mediawiki
- bip-0125.mediawiki
BIP125 has been in Accepted / Proposed status since at least 8 years and could use a status update.
At the same time, the network appears to have largely adopted full RBF by default. See https://github.com/bitcoin/bitcoin/pull/30493 and https://github.com/bitcoin/bitcoin/pull/30592.
Perhaps this BIP should be updated from Proposed to one of Final, Replaced, or Obsolete. 
Update: Obsolete chosen, per author feedback.
> BIP125: update status of Opt-in Full RBF Signaling to Obsolete

- bip-0388.mediawiki
I found that test vectors in BIP-388 contain errors regarding multipath descriptor derivation.
Also, fixed invalid newline in multipath descriptor derivation doc.
> Fix wrong test vector in BIP-388. Sometimes /<0;1>/* is missing. Sometimes it is incorrectly written as <0,1>.

- bip-0373.mediawiki
- The aggregate pubkey in `PSBT_{IN,OUT}_MUSIG2_PARTICIPANT_PUBKEYS` does not have to appear anywhere in the Taproot output.
- The plain pubkeys in `PSBT_IN_MUSIG2_PUB_NONCE` and `PSBT_IN_MUSIG2_PARTIAL_SIG` must be either the output pubkey, or appears in a script, and not the internal key.
> BIP373: Clarify where keys in MuSig fields may appear in the Taproot output

- bip-0085.mediawiki
* Address lingering feedback from #1679 
* Complete words table for application 39' (I could bump to semver 1.4.0. for this but that seems excessive)
* Reorder sections to be more standard
* Convert discussion to standard footnote
> BIP-85: formatting and changelog updates, and add word cases for application 39'

- README.mediawiki
- bip-0349.md
- bip-internalkey.md
OP_INTERNALKEY is a new BIP342 tapscript only opcode (upgraded using OP_SUCCESS semantics) that takes bytes 1-32 (0-index, inclusive) from the BIP341 taproot control block and places them on the stack. This BIP describes that behavior.
> Add BIP 349: OP_INTERNALKEY

- bip-0119.mediawiki
Second sentence in the second paragraph of the Forwarding Addresses section, had a slight grammatical error that needed correcting. 
Helpful for the flurry of interested people keen on reviewing the BIP (i.e. Institutions, non-English nation-states)
> Updated grammatical error relating to Forwarding Addresses

- README.mediawiki
- bip-0348.md
This BIP is based on the BCH OP_CHECKDATASIG work, as well as postings from the bitcoin dev mailing list in [this thread](https://www.mail-archive.com/bitcoin-dev@lists.linuxfoundation.org/msg10211.html). Some differences appear due to the activation of bips 340, 341, and 342 (taproot) since those were developed.
OP_CHECKSIGFROMSTACK is an OP_SUCCESS upgrade available only in BIP342 tapscript.
> BIP 348: OP_CHECKSIGFROMSTACK

- README.mediawiki
- bip-0125.mediawiki
Discussing #1692 with @luke-jr, realized that we may not have followed BIP2 process when updating BIP125 from Proposed to Obsolete.
Per BIP2:
"A Proposed BIP may progress to Final only when specific criteria reflecting real-world adoption has occurred."
"When a Final BIP is no longer relevant, its status may be changed to Replaced or Obsolete (which is equivalent to Replaced). This change must also be objectively verifiable and/or discussed."
BIP125 saw real-world adoption, so it would make sense to update it from Proposed to Final. But arguably not from Proposed to Replaced/Obsolete as done in #1692, as it was not final, not replaced by another BIP, and still relevant (also supported in at least one bitcoin implementation).
> BIP125: update status to Final

- bip-0373.mediawiki
While reviewing https://github.com/bitcoin/bitcoin/pull/31247 a while ago I noticed that the mentioned public keys in the PSBT fields of this BIP are quite confusing. This is mostly due to a non-consistent mention of types (plain vs. x-only) and a purpose that is sometimes missing. This PR aims to improve this in the following ways:
- be specific about the purpose of pubkey types in PSBT fields ("plain pubkey" alone doesn't say a lot, especially if it's used repeatedly within a field; explicitly call it "aggregate pubkey" or "participant pubkey" if applicable)
- replace all uses of "plain pubkey" by "compressed pubkey" (the only category that should matter is whether the pubkey type is "x-only" or "plain")
- use consistent word order, e.g. prefer "compressed aggregate public key" over …
> BIP-373: denote different public key types/purposes consistently

- bip-0125.mediawiki
Given that both BIPs are now final, calling them drafts, seem very stale.
> BIP125: Update description of BIPs 68 and 112

- bip-0087.mediawiki
- bip-0088.mediawiki
- bip-0098.mediawiki
This pull request addresses several typographical errors found in the BIP documents:  
- Corrected "shemes" to "schemes" in BIP-0088.  
- Fixed "publicitly" to "publicly" in BIP-0088.  
- Replaced "unambigouos" with "unambiguous" in BIP-0088.  
- Corrected "message paddding" to "message padding" in BIP-0098.  
- Adjusted "inbetween" to "in between" in BIP-0087.  
These changes ensure the clarity and accuracy of the documentation.
> Fix typos in BIPs 87/88/98

- bip-0370.mediawiki
- bip-0373.mediawiki
This PR fixes several typographical errors in two BIP documents.
Changes in bip-0370.mediawiki:
- "phrase" → "phase"
- Corrects the usage of "design phrase" to "design phase", as "phase" is the correct term for a stage or period in a process
Changes in bip-0373.mediawiki:
- "dervation" → "derivation"
- Fixes misspelling of "derivation" in the context of BIP32 key derivation
- "if," → "of,"
- Corrects grammatical error in the sentence about PSBT field awareness
Rationale:
These changes improve the technical accuracy and readability of the documentation:
1. "Phase" is the correct term for describing a stage in the design process
2. "Derivation" is the proper technical term for BIP32 key generation
3. "Of" is the correct preposition in the context of being aware of something
> Fix typos in BIP-0370 and BIP-0373

- bip-0039/bip-0039-wordlists.md
Corrected terminology: "double vocals" → "double vowels"
1. The rule being described refers to spelling and letter patterns, specifically when two vowel letters appear together.
2. The term "vowels" is the proper linguistic term for such letters, while "vocals" is incorrect in this context.
3. The example "lineetta" demonstrates a double vowel pattern ('ee').
> BIP39: fix word in Italian wordlist special considerations

- bip-0388.mediawiki
This required a few changes in the grammar describing descriptor templates: the single symbol `KP` is no longer enough to cleanly represent the syntax. Therefore, it's now replaced by a more fine-grained symbol hierarchy:
- `KEY`, mapping 1-on-1 to `KEY` expressions of descriptors
- `KP`, key placeholders, that represent a single root key, or an aggregate musig key; regardless of the nature of the key, key placeholders are what is followed by `/**` or `/<M;N>/*`.
- `KI`, key index, the actual "pointer" to the key information vector.
While the validity checks to avoid pubkey reuse before this change were feasible by looking at all the `@i` expressions in the descriptor template, they are now at the level of the KEY expressions, by comparing their key placeholders.
This means that the specs …
> 388: Add support for `musig` in descriptor templates

- bip-0340/test-vectors.py
The `lift_x` function in the BIP and the reference implementation expect an integer to be passed rather than a byte array.
Can be tested with:
```
$ python3 test-vectors.py > expected.csv
$ diff test-vectors.csv expected.csv
```
On master, the first call fails with
```
Traceback (most recent call last):
File "/home/thestack/bips/bip-0340/test-vectors.py", line 267, in <module>
vector0(),
^^^^^^^^^
File "/home/thestack/bips/bip-0340/test-vectors.py", line 30, in vector0
pubkey_point = lift_x(pubkey)
^^^^^^^^^^^^^^
File "/home/thestack/bips/bip-0340/reference.py", line 72, in lift_x
if x >= p:
^^^^^^
TypeError: '>=' not supported between instances of 'bytes' and 'int'
```
> BIP-340: fix `lift_x` calls in test vector generation script

- bip-0374/reference.py
Both generating and verifying a proof allows for specifying a custom generator point G. But that custom generator point was not passed into the dleq_challenge function, resulting in the default (secp256k1) generator point to be used. This lead to the test vectors being incorrect.
Noticed this while re-implementing DLEQ proof generation and verification in Golang.
> bip-0374: fix challenge generation, use correct generator point

- bip-0374/reference.py
- bip-0374/secp256k1.py
by adding to each a python shebang and changing their file permissions from 644 to 755, as mentioned in https://github.com/bitcoin/bips/pull/1734#issuecomment-2564476828.
These files don't need to be executable in order to run `gen_test_vectors.py` and `run_test_vectors.py` but it is helpful to allow developers to invoke them directly.
Before:
```bash
$ ./reference.py 
zsh: permission denied: ./reference.py
```
After:
```bash
$ ./reference.py 
```
> BIP374: update reference.py and secp256k1.py to be executable

- bip-0158.mediawiki
https://github.com/btcsuite/btcutil/blob/master/gcs leads to a broken link. I'm assuming the correct replacement is at https://github.com/btcsuite/btcd/tree/master/btcutil/gcs since `btcutil` is a sub-package in `btcd`, as stated in https://github.com/btcsuite/btcutil/tree/master?tab=readme-ov-file
> BIP158: fix btcutil gcs broken link.

- bip-0372.mediawiki
- bip-0381.mediawiki
Merges and improves on the editorial spelling/grammar suggestions in https://github.com/bitcoin/bips/pull/1720.
Closes https://github.com/bitcoin/bips/pull/1720.
> BIP372, BIP381: editorial fixups

- bip-0345.mediawiki
`OP_SUCCESS188` is `0xbc`, not `0xbb`.
> BIP345: fix OP_SUCCESS188 hex value

- bip-0388/wallet_policies.py
`return` was being used incorrectly to handle an exception. Instead of returning the exception, it should be raised using `raise`.
> BIP388: Fix incorrect use of return for raising exception

- bip-0039.mediawiki
These are required for legal use, and also per BIP-2, and they avoid user confusion as seen in https://github.com/bitcoin/bips/pull/1395#issuecomment-2393915807.
Choice of MIT license per BIP author feedback in https://github.com/bitcoin/bips/pull/1395#issuecomment-2393930721.
The license omission was likely an oversight.
BIP-39 predates BIP-2 by 2-3 years. BIP-1 (in force at the time, since superseded by BIP-2) did require a copyright or public domain section.
> BIP39: add license and copyright section

- bip-0174.mediawiki
- bip-0375.mediawiki
Assuming a by one increment in the keytype of the silent payments output fields, the following numeral to 0x09 in the hexadecimal system is 0x0a, not 0x10.
> BIPs 174 and 375: fix PSBT_OUT_SP_V0_LABEL value

- bip-0348.md
- bip-0349.md
- bip-0379.md
- scripts/buildtable.pl
@ajtowns pointed out in his [BIP 3 review]( https://github.com/bitcoin/bips/pull/1712#discussion_r1946113305) that the author email addresses in the preamble of BIPs in markdown format were not being rendered.
> Render author email addresses in markdown BIPs

- bip-0390.mediawiki
BIP 390 was assigned on [2024-06-04](https://github.com/bitcoin/bips/pull/1540#pullrequestreview-2097428451)
> 390: Fix created date

- bip-0329.mediawiki
If the goal is solely to move labels between cooperating wallets, then previously defined values are the absolute minimum needed. However, wallet data exports can serve other purposes and many values associated with
addresses, transactions and outputs are already on-hand for the wallet generating the export, and yet would be hard or impossible for importing tools to reconstruct.
This PR proposes a bunch of optional fields that could be useful to users of this data. All are optional.
> BIP329: add optional data fields, fix a JSON type

- bip-0329.mediawiki
@jonatack Just adding the minor edits you suggested previously which @doc-hex approved, along with another small edit to clarify the address heights specification to align with transaction height.
> BIP329: PR 1750 follow-up edits

- bip-0159.mediawiki
A few clarifications following a discussion with BIP author Jonas Schnelli yesterday and then thanks to review feedback from both Jonas and Murch.
These are compatible with the reference implementation in the BIP and with the current implementation in Bitcoin Core.
It is worthwhile to read the discussion in reference implementation https://github.com/bitcoin/bitcoin/pull/10387 (particularly https://github.com/bitcoin/bitcoin/pull/10387#discussion_r156861038).
> BIP159 updates

- bip-0119.mediawiki
The linter is raising with the following (e.g., in #1780 and #1783) that is resolved by this patch.
```bash
~/bitcoin/bips$ typos
error: `TYP` should be `TYPO`
--> ./bip-0119.mediawiki:594:73
|
594 | is set to CTVHASH_ALL. Other programs could be added similar to SIGHASH_TYPEs.
```
> BIP119: appease typos linter

- bip-0094.mediawiki
Addresses https://github.com/bitcoin/bips/pull/1781#discussion_r1985677753 ("Parameters"), writes "Testnet 4" in the same manner as the BIP author, and removes an extra EOL space.
> BIP94 PR1781 editorial fixups

- bip-0348.md
Unknown key types are defined as part of the Tapscript opcodes' semantics, in bip-0342. Not bip-0341.
> bip-0348: correct BIP number in referencing unknown key types

- bip-0094.mediawiki
In this commit, we restructure the specification section to make the consensus rules clearer and more scannable. The previous section interleaved commentary and historical tidbits with the motivation and new rules, making it difficult to quickly identify the exact rule changes.
A high level over view the intended changes is as follows:
- Numbers each rule for easier reference
- Adds explicit "Rule Specification" sections
- Uses structured lists with MUST statements following RFC/IETF conventions
- Provides a clear problem statement before each solution
- Separates explanatory text from the actual rules
I was reviewing a PR to btcd to implement testnet4, and found it hard to scan the BIP to find the actual new rules, which inspired this PR.
> BIP-0094: reformat specification section for clarity and readability

- README.mediawiki
- bip-0060.mediawiki
According to BIP-0002, any person can request this.
> Reject BIP-0060 (three years inactivity)

- bip-0158/gentestvectors.go
Fix up error message:
- `"Couldn't get block hash"` → `"Couldn't get block data"` for better clarity
Also minor grammar edit in code comment:
- `"checks for filter size of DefaultP"` → `"checks the filter size of DefaultP"`
> BIP158: minor error message fixup in `gentestvectors.go`

- bip-0032.mediawiki
*Replaces https://github.com/bitcoin/bips/pull/727 with with cherry-picked 81644ddfa131bb0e387ead2cc309ca18e57542b1; note that BIP32 has status `Final`. The description below is copied from that PR.*
Base58chk-encoded extended keys are always 111 characters long.  Amend wording of BIP32 accordingly.
**Diff:**
-This results in a Base58-encoded string of up to 112 characters.
+This results in a Base58-encoded string of exactly 111 characters.
**Proof:**
Version bytes: `0x0488b21e` (“xpub”), `0x0488ade4` (“xprv”), `0x043587cf` (“tpub”), `0x04358394` (“tprv”)
Largest version byte is `0x0488b21e`, smallest `0x04358394`.
Largest “possible” key:
```
kL = 0x0488b21effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff …
```
> BIP32 amendment: base58chk-encoded extended keys are always 111 chars

- bip-0379.md
Replace `SIZE <20> EQUALVERIFY` with `SIZE 32 EQUALVERIFY` for `sha256(h)`, `hash256(h)`, `ripemd160(h)`, and `hash160(h)`.  
`sha256`/`hash256` produce 32 bytes, not 20, so the original size check is incorrect.
> BIP379: add missing hexadecimal notations

- bip-0067.mediawiki
- bip-0301.mediawiki
The original master file has been changed, and the line numbers referenced by the original URL are no longer accurate. Therefore, a fixed permanent link is used to replace it. The purpose of adopting a permanent link is to prevent the line numbers originally pointed to by the URL from becoming inaccurate again when further changes are made to the master branch.
> BIPs 67 and 301: fix links

- bip-0069/bip-0069_examples.py
Typo fixup in `bip-0069/bip-0069_examples.py`:
`disinct` -> `distinct`
> BIP69: typo fixup in bip-0069_examples.py

- README.mediawiki
- bip-0003.md
I was [finished with my planned work](https://gnusha.org/pi/bitcoindev/25449597-c5ed-42c5-8ac1-054feec8ad88@murch.one/) on 2025-02-03, and after a few more rounds of review, BIP3 got merged on 2025-02-20.
I have not received any additional review comments or change suggestions in over three weeks, so it seems to me that this proposal may be complete and ready for adoption, although amendments are of course still possible if anyone has further review, concerns, or suggestions. Please feel free to leave comments here or write to the mailing list.
Otherwise, I posit that this proposal is ready to be moved to Proposed.
> BIP3: Move to Proposed

- bip-0003.md
Hi! I fixed broken links in `bip-0003.md`. The issue was caused by incorrect letter casing in file references (`BIP-0002.mediawiki` → `bip-0002.mediawiki` and `BIP-0123.mediawiki` → `bip-0123.mediawiki`). The links have been updated to match the correct filenames, ensuring proper navigation.
> BIP-3: update dead link in `bip-0003.md`

- bip-0324/reference.py
> BIP-0324: fix typo

- bip-0015.mediawiki
- bip-0020.mediawiki
- bip-0035.mediawiki
This PR makes the following changes:
1. BIP-0015: Fixes typo in the word "that" and improves readability of the address example explanation
2. BIP-0020: Improves message text clarity by adding "is" in the QR code scanning message
These are minor text improvements that don't change the technical content of the BIPs but make them more readable and grammatically correct.
> BIP-0015 and BIP-0020: fix typos and improve text clarity

- bip-0078.mediawiki
- bip-0329.mediawiki
This pull request corrects several grammatical errors and typos in BIP-0329.mediawiki and BIP-0078.mediawiki files.
Fixed incorrect word "independant" to "independent" in line 164:
- * <tt>keypath</tt>: The data needed to build full descriptor down to the specific address.  This extends <tt>origin</tt> with the final two components that are unhardened (in the typical case, assuming BIP-84).  Provide string <tt>/1/123</tt> for <tt>wpkh([d34db33f/84'/0'/0'/1/123])</tt>. If the first character is not <tt>/</tt>, then it should be interpreted as a full descriptor, independant of <tt>origin</tt> (if any).
+ * <tt>keypath</tt>: The data needed to build full descriptor down to the specific address.  This extends <tt>origin</tt> with the final two components that are unhardened (in the typical …
> BIPs 78 and 329: minor grammar and typo fix-ups

- bip-0374/reference.py
- bip-0374/secp256k1.py
This commit implements the subtraction operator (__sub__) for the GE (Group Element) class in the secp256k1.py file as requested in the TODO comment in reference.py.
The implementation is straightforward, leveraging the existing __neg__ method to define subtraction as addition with the negated element: self + (-a).
After implementing the operator, the code in reference.py was simplified by replacing expressions like:
s * G + (-e * A) with s * G - e * A
This makes the code more readable and directly matches the mathematical notation used in the BIP-0374 specification.
> BIP374: add subtraction operator for GE class

- bip-0099.mediawiki
This PR updates the link to the experimental hardfork-timewarp-0.11 branch, which was a PoC for a TimeWarp hardfork fix.
> BIP 99: update invalid link to hardfork-timewarp-0.11 branch

- README.mediawiki
- bip-0054.md
This is a BIP draft for a Consensus Cleanup soft fork.
This proposal builds upon Matt Corallo's 2019 [proposal](https://github.com/TheBlueMatt/bips/blob/7f9670b643b7c943a0cc6d2197d3eabe661050c2/bip-XXXX.mediawiki), which i set to revive at the end of 2023. I eventually shared my research in a [Delving Bitcoin post](https://delvingbitcoin.org/t/great-consensus-cleanup-revival/710) in early 2024 (along with a [semi-private companion post](https://delvingbitcoin.org/t/worst-block-validation-time-inquiry/711) for the redacted sensitive details). A number of people contributed ideas, testing and otherwise fruitful discussion. This led to settling on a list of mitigations, which [i updated the mailing list about](https://gnusha.org/pi/bitcoindev/jiyMlvTX8BnG71f75SqChQZxyhZDQ65kldcugeIDJVJsvK4had …
> BIP 54: Consensus Cleanup

- bip-0048.mediawiki
BIP48 currently defines script types only for p2wsh and p2sh-p2wsh, but not for the newer p2tr.
This PR proposes defining the the script_type for p2tr as `3`, to provide a clear standard for the derivation to use in p2tr scripts.
> BIP48: Add p2tr script type derivation

- README.mediawiki
- bip-0177.mediawiki
This BIP proposes redefining the bitcoin unit of account to represent the protocol’s smallest indivisible unit as “1 bitcoin,” eliminating the need for decimal-based UI conventions.
- Type: Informational
- No changes to consensus rules or supply
- Matches Bitcoin’s native integer representation
- Includes multi-phase rollout recommendations
Authored by: John Carvalho (@BitcoinErrorLog)
Mailing list:
https://groups.google.com/g/bitcoindev/c/YwF-djZi1Bo/m/nIkyuClEAgAJ
> BIP177: Redefine Bitcoin’s Base Unit

- bip-0048.mediawiki
Follow-up to https://github.com/bitcoin/bips/pull/1835.
> BIP48: Add P2SH-P2WSH and P2TR mainnet examples

- README.mediawiki
- bip-0345.mediawiki
This proposal has basically been replaced by #1793. See https://delvingbitcoin.org/t/withdrawing-op-vault-bip-345/1670 for rationale.
> BIP-345: withdraw

- bip-0372.mediawiki
Fixed incorrect preposition in key tweaking explanation:
- `multiplied on` → `multiplied by`
- Clarified BIP-340 key serialization:
- `appending '02'` → `appending '0x02'`
- Removed unnecessary trailing comma in the list of output types
- Removed erroneous semicolon after URL
> BIP-372: Fix references and links formatting and minor typos

- bip-0331.mediawiki
Since the version is denoted as uint64, the size should be 8 bytes.
> bip-0331: correct size of version field in sendpackages

- README.mediawiki
- bip-0048.mediawiki
As discussed on https://github.com/bitcoin/bips/pull/1835#pullrequestreview-2837827946, the addition to P2TR was incompletely specified, and BIP48 should no longer be changed. Therefore, I propose to revert the changes, and to move BIP48 to final instead.
> BIP48: Partially revert recent changes, move to final

- bip-0069.mediawiki
Fixes an out-of-date link:
before
https://github.com/btcsuite/btcutil/blob/master/txsort/txsort.go
after
https://github.com/btcsuite/btcd/blob/master/btcutil/txsort/txsort.go
> BIP69: fix link

- bip-0021.mediawiki
Clarify to readers that the addresses used in the examples are intentionally invalid to prevent accidental transactions.
> BIP21: clarify that example addresses are intentionally invalid

- bip-0383.mediawiki
Fixes the output script template to correctly include the `n` value.
Also changed how the minimal encoding is described to just describe it rather than an exhaustive list.
Alternate to #1860
> 383: Fix output scripts and reword minimal encoding explanation

- bip-0379.md
- bip-0381.mediawiki
- bip-0382.mediawiki
- bip-0383.mediawiki
- bip-0384.mediawiki
- bip-0385.mediawiki
- bip-0386.mediawiki
- bip-0387.mediawiki
- bip-0389.mediawiki
- bip-0390.mediawiki
Clarifies the restrictions on KEY expressions around when child derivation is allowed.
Also added a `Requires` header to all of the descriptor BIPs since they require reading 380 first.
> 390: clarifications on KEY expression restrictions

- bip-0380.mediawiki
Me and my students noticed a discrepancy in the test vectors and specification regarding the allowed characters denoting hardened nodes. The [BIP380](https://github.com/bitcoin/bips/blob/master/bip-0380.mediawiki) specs allows all three `h`, `'` and `H`, in particular the specs read:
> In the above specification, the hardened indicator `h` may be replaced with alternative 
hardened indicators of `H` or `'`.
However, the following is then an **invalid** test vectors:
> [deadbeef/0H/0H/0H]0260b2003c386519fc9eadf2b5cf124dd8eea4c4e68d5e154050a9346ea98ce600
Thus, I've added new test vectors allowing `H` and removed the inconsistent one. 
However, I am far from claiming that this is the **correct** way how to handle this. I've checked that …
> BIP380: make specs consistent about hardened indicators

- bip-0443.mediawiki
This fixes some mistakes in the python pseudocode (that described an older version that is not aligned to the [draft implementation](https://github.com/bitcoin/bitcoin/pull/32080) in core), and fixes some minor other details.
Commit e4e2b7ccd10af0ad0fdab6358461567326ee21e8 also adds a paragraph to clarify that fees are expected to be paid exogenously. While not specific to CCV and rather common to most/all covenant proposals, it was suggested in the [comments of the previous PR](https://github.com/bitcoin/bips/pull/1793#issuecomment-2898403846) to have an explainer (cc @Sjors).
> 443: Fix some mistakes, and add paragraph on fees

- bip-0388.mediawiki
fix: descriptor in "Taproot wallet policy with sortedmulti_a and a miniscript leaf" test vector which incorrectly uses `@0` from keys info without key origin derivation
> BIP-0388: Fix test vector

- bip-0077.md
This PR addresses the concerns raised in #1885 with regards using `+` as a delimiter, by switching to `-`. Some URI libraries implement RFC 1866's (HTML 2.0) "keyword" delimitation in query parameters by decoding `+` as ` ` unconditionally, which necessitates kludgy workarounds.
Additionally fragment parameters must now ordered lexicographically (instead of reverse), the motivation for a canonical ordering was to reduce implementation fingerprinting concerns, but the reverse lexicographical ordering was specified simply because that was the behavior that was already implemented in PDK. Since that is somewhat surprising and the delimiter change breaks backwards compatibility anyway, the marginal cost in terms of compatibility of reducing the surprisingness of the reversed ordering is …
> BIP 77: Delimit fragment params with  `-` instead of `+`

- bip-0069/bip-0069_examples.py
Corrected a typo in the output_cmp function where the non-existent function bytearray_cmp was called. Changed it to the correct function name bytearr_cmp to ensure proper output comparison and prevent runtime errors. This fix improves code reliability and consistency.
> BIP69: fix function name typo in example code

- bip-0352.mediawiki
While this is statistically improbable, e.g., we don't yet know of a hash preimage that results in an output = 0 or greater than the curve order, we still want to be explicit on how to handle this (same as we do for the tweaks themselves).
> BIP352: be explicit for the input_hash corner case

- bip-0003.md
based on @real-or-random's https://github.com/bitcoin/bips/pull/1892#issuecomment-3051961323.
Also a couple of minor BIP3 touch-ups.
> BIP3: drop optional License Code header

- bip-0345.mediawiki
The recovery scriptPubKey needs to be prefixed with its CompactSize-encoded length when computing the sPK hash.
I verified this by:
- Checking the [functional tests](https://github.com/jamesob/bitcoin/commit/5e59c074703f0913db7ee004b99d086857d10ad6#diff-65a47d52759ba7800338bacb3005836bdc0f3962de356621e5c50887c85c4af8R1407-R1409), where `recovery_spk_tagged_hash()` is implemented using [`ser_string()`](https://github.com/bitcoin/bitcoin/blob/af3dee0b8d456a8aa9ade9c6e7f4283a90590eae/test/functional/test_framework/messages.py#L148-L149) which adds the CompactSize-encoded length prefix
- Using an [implementation in Minsc](https://min.sc/v0.3/#gist=d8ac58dadc7377c3e231b4c7735ee5c5) to construct a [transaction](https://mutinynet.com/tx/944db06a37842fea9f7db117a0118221ee4bbdb0116354c562adcd12edaa …
> BIP 345: Fix OP_VAULT_RECOVER specification for the recovery-sPK-hash

- bip-0374/run_test_vectors.py
Remove leftover debug print statement that was printing private keys(seckey_a_hex) to console during test execution. Improves test output readability and consistency.
> BIP374: remove debug print from test runner

- bip-0345.mediawiki
broken: https://github.com/instagibbs/bips/blob/ephemeral_anchor/bip-ephemeralanchors.mediawiki
correct: https://github.com/instagibbs/bips/blob/527b007dbf5b9a89895017030183370e05468ae6/bip-ephemeralanchors.mediawiki
> BIP345: fix broken link

- bip-0352/reference.py
Remove from itertools import permutations which is not used anywhere
Re-checked the codebase: no calls to permutations(...)
> BIP352: remove unused import from reference.py

- bip-0003.md
Picks up #1931 and adds a commit to update the MIT license name. Changes:
- Fix up license URLs with 301 redirects
- Add MIT-0 License
- Update MIT license name per https://opensource.org/license/MIT and https://spdx.org/licenses/MIT
> BIP3: license section updates

- bip-0002.mediawiki
- Update MIT license name per https://opensource.org/license/MIT and https://spdx.org/licenses/MIT
- Fix up license URLs with 301 redirects
> BIP2: license section fixups

- README.mediawiki
- bip-0327.mediawiki
- bip-0353.mediawiki
A BIP status of Active is only for Process BIPs.
- BIP 327 should be Final, not Active.
- BIP 353 has an open PR with test vector additions, should be Proposed.
> BIP327,353: Update to Final and Proposed instead of Active
