bitcoin/bips

bip-0065.mediawiki

fixing typo

---

README.mediawiki
bip-0067.mediawiki
bip-0090.mediawiki

BIP for standard multisignature P2SH addresses given m and a set of public keys.
Bip90 is just a number which doesn't collide, I will request one via the mailing list now.

BIP: Deterministic multi-signature P2SH addresses

---

README.mediawiki
bip-0068.mediawiki

BIP number assigned here:
https://www.mail-archive.com/bitcoin-development@lists.sourceforge.net/msg08340.html

Add BIP 68: Consensus-enforced transaction replacement signalled via sequence numbers

---

bip-0045.mediawiki

- fix examples
- fix address discovery section
- fix purpose to 45
- mention difference with bip-0044

Update bip45 based on comments by dskloet

---

bip-0065.mediawiki

There should be a dummy 0 in the scriptSig for CHECKMULTISIG

Dummy 0 in scriptSig for CHECKMULTISIG

---

bip-0066.mediawiki

"verifcation" -> "verification".

Corrected spelling of one word.

---

bip-0066.mediawiki

If #169 is not able to merged,  then lets bump this puppy.

bip66: change status to final

---

BIP-1xx.mediawiki
bip-0106.mediawiki

Transferred from https://github.com/UpalChakraborty/bips/blob/master/BIP-DynamicMaxBlockSize.mediawiki

BIP 106: Dynamically Controlled Bitcoin Block Size Max Cap

---

README.mediawiki
bip-0112.mediawiki
bip-csv.mediawiki

BIP112: CHECKSEQUENCEVERIFY

---

bip-0068.mediawiki

Including the removal of bit inversion and the allocation of future soft-fork bits.
Includes and obsoletes #172.

Rewrite BIP 68 to reflect current state of pull request #6312

---

bip-0009.mediawiki
bip-wuille-todd-maxwell-russell.mediawiki

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-September/010998.html
Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>

versionbits: the BIP.

---

bip-0009.mediawiki

As discussed here:
http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-September/011275.html
Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>

BIP 009: Minor revision to extend bit into lockin period.

---

README.mediawiki

Let's try to make this a requirement before merge. No stealth BIPs :)

Add BIP0009 to index

---

bip-0112.mediawiki

This pull request updates BIP112 to the BIP68 and adds more usecase examples.

[WIP] Update BIP112

---

bip-0112.mediawiki

This PR adds more usecases to the motivation section.

Update BIP112 examples

---

bip-0112.mediawiki

Also, update git repo to point to the associated pull request.

Clarify portions of text & example scripts

---

bip-0121.mediawiki

"unneccesarily" => "unnecessarily"

Spelling fix.

---

README.mediawiki
bip-0123.mediawiki

Please assign number. BIP123 would be nice.

Bip classification

---

README.mediawiki
bip-0102.mediawiki

* Fix index, 101 -> 102
* Latest BIP 102 updates:  Remove now-past date.  Replace with miner vote.

BIP 102: Add miner vote. Fix index.

---

README.mediawiki
bip-0130.mediawiki
bip-sendheaders.mediawiki

This is in substantially the same form as proposed on the mailing list and discussed on IRC.  I'll update this pull after a BIP number is assigned.
@theuni -- perhaps we can discuss any outstanding concerns with this approach in this PR?

New BIP for "sendheaders" p2p message

---

bip-0022.mediawiki

typo fixed

---

README.mediawiki
bip-0099.mediawiki

Continues #181, including some things that were left out by accident.

Bip99: Improvements

---

bip-0065.mediawiki

Fix various wording issues, like obsolete terms, typos, unclear wording etc.

BIP65 wording fixes

---

bip-0065.mediawiki

Full description of the behavior of OP_CLTV

---

bip-0068.mediawiki

BIP68 and BIP113 will be deployed together which simplifies the specification slightly

BIP68: update specification to assume MTP

---

README.mediawiki
bip-0001.mediawiki

@gmaxwell asked that I take over BIP number assignments

BIP 0001: Change BIP editor to Luke Dashjr

---

dynamicblocksize.mediawiki

+ 2 phase plan for increasing the block size
+ Will update with BIP number if/when assigned one

BIP 107: Dynamic block size proposal

---

bip-segwitaddress.mediawiki

Request for BIP number for "Address Format for Witness Program"

BIP 142: Address Formats for Witness Program

---

README.mediawiki
bip-0124.mediawiki

Defines a generalized script template format for wallet interoperability.

BIP 124: Hierarchical Deterministic Script Templates

---

bip-0141.mediawiki

Very likely that this won't be done correctly; better to not suggest it at all.

Remove merge-mining suggest re: witness nonce

---

bip-andychase.mediawiki

Previous discussions:
* https://gist.github.com/andychase/dddb83c294295879308b
* https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-September/010948.html
* https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-September/010914.html
I would like to be assigned a number please! Thanks.

BIP 132: Add Committee-based BIP Acceptance Process

---

bip-0141.mediawiki

Tidy up Witness Program section

---

bip-0144.mediawiki

Adding a missing reference to BIP 141 for clarity.

Adds a missing BIP 141 segwit BIP reference

---

bip-0122.mediawiki

Grammar, punctuation and labeling improvements meant to clarify the BIP and improve readability.

Improvements to BIP 122

---

bip-0068.mediawiki

This patch syncronised latest implementation
Adds comments, adds assert()

Minor update of implementation for BIP68

---

.travis.yml
scripts/buildtable.pl

This needs an admin to actually enable Travis...

Travis: Initial formatting tests

---

bip-0050.mediawiki

@gavinandresen This look okay? Particularly note the addition of the public domain release.

bip-0050: Final update to what actually occurred

---

bip-0068.mediawiki

Update BIP68 implementation to match spec

---

README.mediawiki
bip-0011.mediawiki
bip-0014.mediawiki
bip-0021.mediawiki
bip-0022.mediawiki
bip-0023.mediawiki
bip-0031.mediawiki
bip-0032.mediawiki
bip-0034.mediawiki
bip-0035.mediawiki
bip-0037.mediawiki
bip-0065.mediawiki

These seem to meet the criteria for Final, and are already Accepted status.

Promote Accepted->Final BIPs 11, 14, 21, 22, 23, 31, 32, 34, 35, 37, 65

---

bip-0112.mediawiki

Fix IsSuperMajority name, update to reflect new PR number.

ISM: Proper case, update PR number

---

README.mediawiki
bip-0101.mediawiki

It is clear that BIP101 will not be adopted, so I'm withdrawing it.

Withdraw BIP 101 proposal

---

README.mediawiki
bip-0133.mediawiki

133 assigned by @luke-jr 
See mailing list discussion at:
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-February/012449.html

BIP 133: feefilter message

---

bip-0131.mediawiki

So many people are saying this BIP is bad because it encourages address re-use. I added a paragraph clarifying how address re-use is affected by this BIP.

Added paragraph about address re-use for BIP131

---

bip-0009.mediawiki

Suggested by @rustyrussell and @morcos.

Small improvements to BIP9

---

README.mediawiki
bip-0142.mediawiki

BIP142 will not be deployed with BIP141 at the same time. Initially, people are expected to use P2SH segwit, or payment protocol for native segwit

BIP142: Deferred

---

README.mediawiki
bip-0002.mediawiki

Apparently this cannot achieve consensus for now, so shelving it until something changes.

Defer BIP 2

---

bip-mast.mediawiki

This is a post-segwit BIP to implement Merkelized Abstract Syntax Tree

BIP 114: Merkelized Abstract Syntax Tree

---

bip-0047.mediawiki
bip-0114.mediawiki

Define a bloom filter-based notification method that does not use notification addresses.

BIP-0047: version 2 payment codes

---

bip-0141.mediawiki

Add rationale of block cost
Change the name of "witness nonce" to "witness reserved value"
Update link to reference implementation
Formatting

BIP141 clarifications and formatting

---

bip-0009.mediawiki

Split out of #365 (ie, without segwit and misc changes)

BIP 9: GBT updates for versionbits

---

bip-0009.mediawiki
bip-0009/assignments.mediawiki

Add a place to track various BIP9 deployment proposals.
As per IRC meeting http://www.erisian.com.au/meetbot/bitcoin-core-dev/2016/bitcoin-core-dev.2016-05-05-19.01.html

Add BIP9 assignments

---

bip-0050.mediawiki

Typo in change to BIP50

---

bip-0141.mediawiki

Footnotes to clarify some special conditions which witness scripts will fail @sipa @instagibbs @gmaxwell

BIP141 script failure clarifications

---

bip-0032.mediawiki

Added a new Java implementation.

Proposed a new Java implementation link

---

bip-0039.mediawiki

BIP 39 mnemonics are featured quite prominently in the UI as well.

BIP 39: link BitcoinJS & blockchain.info implementation

---

bip-0141.mediawiki

analogue to https://github.com/bitcoin/bips/commit/ecfb7ebbca3488cd4c1e11210cbc5914a9228c67

BIP-0141: Link to permanent PR of reference implementation

---

bip-0021.mediawiki

This PR adds a Swift Library to parse `Bitcoin Payment URI`.

Add Swift Library

---

README.mediawiki
bip-0134.mediawiki
bip-flexibleTransactions.mediawiki

Introducing Flextrans. Requesting a BIP number assignment. Thank you!

BIP 134: Flexible Transactions

---

bip-0134.mediawiki

Take all feedback items into account.

Fixes to 0134

---

bip-0044.mediawiki

The C#  implementation is now open source

Adding the source code for CoinVault

---

bip-0144.mediawiki

Found these missing while working on https://github.com/bitcoin/bitcoin/pull/8880 .
Ping @sipa @codeshark.

bip-0144: Add enum values for MSG_WITNESS_{BLOCK,TX}, MSG_FILTERED_WITNESS_BLOCK

---

bip-0049.mediawiki

place-holders replaced and testvectors calculated

BIP49 - calculate testvector

---

bip-0009/assignments.mediawiki

Update segwit deployment details

---

bip-0134.mediawiki

Many fixes and new features for BIP134

Update the spec following the new developments

---

bip-0067.mediawiki

as requested for preperations for BIP2
@afk11

add Copyright to BIP67

---

README.mediawiki
bip-0109.mediawiki

All proponents of BIP 109 seem to agree it is dead

Update BIP 109 status Draft->Rejected

---

README.mediawiki
bip-0090.mediawiki
bip-buried-deployments.mediawiki

I think this is ready to move forward, can this be assigned a BIP number?

BIP 90: Buried deployments

---

bip-0069.mediawiki

The sentences in the motivation section of BIP69 are duplicated. So I deleted it.

Remove duplication BIP69

---

README.mediawiki
bip-0091.mediawiki
bip-segsignal.mediawiki

Mailing list discussion: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-May/014380.html

BIP 91: Reduced threshold Segwit MASF

---

bip-0039.mediawiki

I used Swift to achieve the BIP39, currently supports Chinese and English. Reference to [NYMnemonic](https://github.com/nybex/NYMnemonic), the third party encryption algorithm library  [CryptoSwift](https://github.com/krzyzanowskim/CryptoSwift) .

Add an implementation of Swift

---

README.mediawiki
bip-0159.mediawiki

The proposal has been submitted to the bitcoin mailing list on May 11th 2017.
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-May/014315.html
Feedback has been received and the proposal has been overhauled.

BIP 159: NODE_NETWORK_LIMITED service bits

---

README.mediawiki
bip-0091.mediawiki
bip-0148.mediawiki
bip-0149.mediawiki

BIP91 -> Final
BIP148 -> Final
BIP149 -> Withdrawn (because it's no longer necessary)

Update BIP status

---

bip-0175.mediawiki

This PR fixing typo "excpet" to "except".

BIP-0175: fixed typo.

---

bip-0039.mediawiki

I'm not affiliated with this implementation but I found it today and it appears to be actively maintained.

rust mnemonic library added

---

bip-0039.mediawiki

Cosmetic fix in 'Other Implementations' section, removed extra spacing.

BIP39: Removed extra spacing

---

bip-0002.mediawiki

"README.specs" was renamed "README.specs.md"

BIP-2: Fix link to Bitcoin Wallet for Android's wallet/README.specs.md

---

bip-0039.mediawiki

Update bip-0039.mediawiki with Go lib

---

bip-0141.mediawiki

BIP141: Add BIP173 to references.

---

bip-0118.mediawiki

Trivial typo fixes to bip-0118

---

bip-reservedbits.mediawiki

This was overlooked in #661
@odarboe @btcdrak @luke-jr

Minor typo fix for "reservedbits" BIP

---

bip-0151.mediawiki

Came to learn - fixed a few things [trivial]

[Trivial]Typos & links fix BIP 151

---

bip-0158.mediawiki

BIP-158: Fixing list formatting and spelling of 'license'

---

bip-0079.mediawiki
bip-bustapay.mediawiki

Requesting a BIP number assignment

BIP 79: Bustapay :: a practical coinjoin protocol

---

bip-0079.mediawiki

I'm in the process of reviewing the contents of the BIP, these are just typo type edits I found while reading. Cheers.

fix typos in bip79

---

bip-0079.mediawiki

As pointed out by Adam Gibson on the bitcoin-dev mailing list.

Fix mistake in bip-0079

---

bip-0044.mediawiki

[BIP 44] Remove 21 Machine Wallet

---

bip-0174.mediawiki

As discussed on mailing list.
@achow101

BIP174: Include suggested sighash check

---

README.mediawiki
bip-0074.mediawiki

According to BIP-0002, anybody can request this change of status after three years of inactivity.

Reject BIP-0074 (three years inactivity)

---

bip-0049.mediawiki

Added version bytes section in parallel with #761.
cc @DanielWeigl

BIP-49 - Add Version Bytes Section

---

bip-0322.mediawiki

Several critical fixes to BIP 322. (Verification was broken, etc.)

BIP-322 major fixes (verification, etc)

---

bip-0013.mediawiki

Don't know if that number 1 is welcome.

Fixed hanging links and removed the number inside the name of the file base58.cpp

---

bip-0174.mediawiki

[bip174] Fix typo in signer pseudo code

---

bip-0174.mediawiki

Just noticed while reading it, don't know if that short PRs are welcome.

Remove a typo in bip-0174

---

README.mediawiki
bip-0100.mediawiki

Constrained-increment hard fork size adjustments.

Add BIP 100, as currently implemented.

---

README.mediawiki
bip-0154.mediawiki

This idea was interesting, but did not receive enough consensus from the community so I am withdrawing the proposal. I or someone else may propose it at a later time, if warranted.

BIP-154: change to withdrawn status

---

bip-0032.mediawiki

NBitcoin official repo has changed.

Update the link to NBitcoin repo

---

README.mediawiki
bip-0008.mediawiki

According to the expiration rules of BIP-0002, I am permitted to request this change even though I am not the author.

BIP-0008 rejected (expired)

---

README.mediawiki
bip-0019.mediawiki

According to expiration rules.

Reject BIP-0019 (expired)

---

README.mediawiki
bip-0033.mediawiki

Requesting this even though I am not the author. BIP-0002 allows me to since 3 years have passed.

Reject BIP-0033 (expired)

---

README.mediawiki
bip-0152.mediawiki

This has been implemented and is in wide usage.

Mark BIP-0152 as Final

---

bip-0325.mediawiki

The genesis block is made static, and the message start is made dynamic based on the sha256d of the block script.
See https://github.com/bitcoin/bitcoin/pull/16411#issuecomment-577999888

bip-325: genesis block/message start

---

bip-0067.mediawiki

it must be OP_CHECKMULTISIG, not OP_CHECKSIG

fixed obvious typo

---

README.mediawiki
bip-0064.mediawiki

This BIP is <s>not implemented</s> obsolete and has expired according to BIP-0002.

Obsolete BIP-0064

---

README.mediawiki
bip-0085.mediawiki

I would like to request a BIP number for this BIP

BIP 85: Deterministic Entropy From BIP32 Keychains

---

README.mediawiki
bip-0078.mediawiki
bip-xxxx.mediawiki

Previous discussion at https://github.com/NicolasDorier/bips/pull/3
Submitting to mailing list.

BIP 78: Add payjoin proposal

---

bip-wtxid-relay.mediawiki

I proposed this on the bitcoin-dev list back in February, so I'd like to request a BIP number be assigned to this.

BIP 339: WTXID-based transaction relay

---

README.mediawiki
bip-0083.mediawiki

According to the expiration rules of BIP-0002, I am permitted to request this change even though I am not the author.

Reject BIP-0083 (three years inactivity)

---

README.mediawiki
bip-0090.mediawiki

The linked Bitcoin Core PR has been merged.

Final BIP-0090 (Buried Deployments)

---

README.mediawiki
bip-0115.mediawiki

According to expiration rules from BIP-0002.

Reject 115 (expired)

---

README.mediawiki
bip-0140.mediawiki

According to expiration rules in BIP-0002.

Reject 140 (expired)

---

README.mediawiki
bip-0156.mediawiki

This BIP proposal has expired according to BIP-0002 expiration rules, and I submit this PR even though I am not an author.

Reject 156 (expired)

---

README.mediawiki
bip-0131.mediawiki

By the power vested in me by BIP-0002, I can request this change even though I am not the author of the BIP.

Reject 131 (expired)

---

README.mediawiki
bip-0134.mediawiki

Per the rules defined in BIP-0002, I request this change even though I am not the relevant BIP author.

Reject 134 (expired)

---

README.mediawiki
bip-0171.mediawiki

I request this because BIP-0002 allows me to. You, yourself is the author, Luke-jr. I will ping noone.

Reject 171 (expired)

---

README.mediawiki
bip-0180.mediawiki

BIP-0002 contains rules that permit non-authors to request expiration. This particular BIP, is a BIP that you @luke-jr yourself have submitted. So I will not notify anybody.

Reject 180 (expired)

---

bip-0339.mediawiki

Thanks @jnewbery for making the initial edits in #961; I went ahead and made the last edit I wanted in here to clarify the specification.

BIP 339 clarifications

---

README.mediawiki
bip-0135.mediawiki

The author is @sanch0panza . There was a Bitcoin Core PR that was never merged, and there has been no progress for three years. So I request this rejection even though I am not affiliated with the BIP, per BIP-0002 expiration rules.

Reject 135 (expired)

---

README.mediawiki
bip-0124.mediawiki

paging @swansontec , @CodeShark 
This BIP has seen no progress in the last three years, and I request its rejection even though I am not an author. BIP-0002 allows this.
I believe its functionality is provided by Miniscript.

Reject 124 (expired)

---

bip-0009.mediawiki

course grained => coarse-grained

Fixing spelling in BIP 9

---

README.mediawiki

Update bip79 status

---

bip-0039/bip-0039-wordlists.md

werbs -> verbs
geografical -> geographical

[Trivial] Fix typos

---

README.mediawiki
bip-0325.mediawiki

A bit late, but AJ ultimately ended up rewriting a big chunk of the proposal for the betterment of mankind and should be listed as one of the authors.
Also requesting status change to "Proposed" as I consider the BIP complete.

bip-325: add Anthony Towns to authors and change status to Proposed

---

bip-0322.mediawiki

It seems more people are leaning towards this being an update to BIP-322 over a new BIP, so I am swapping this to being an update instead of a new BIP.
I am not sure if I like the legacy format compatibility, but people asked for it elsewhere, so I'm keeping it for now.

BIP-322: switch to using tx based approach

---

bip-0085.mediawiki

This PR updates the link to @ethankosakovsky's python library and adds an additional link to a JavaScript implementation.

BIP 0085: Add link to JavaScript library implementation

---

bip-0350.mediawiki

These are edits that I had when #1056 was first opened, but apparently got lost when updated it to include the BIP number. Add them back.

A few lost improvements to BIP350

---

bip-0155.mediawiki

BIP155: Remove external link

---

bip-0039.mediawiki

Add Python-HDWallet package on Other Implementation.

BIP-0039: Add Python-HDWallet package

---

bip-0039.mediawiki

Signed-off-by: koushiro <koushiro.cqx@gmail.com>

Add another Rust implmentation of BIP-0039

---

bip-0008.mediawiki

RE-reading through the BIP i found some sentences to make it seem like LOT was always `true` but it was made optional.

bip8: tiny wording fixups

---

bip-0085.mediawiki

- these minor touch-ups should make the affected sentences easier to read

BIP 85: fixed some typos and minor English mistakes

---

bip-0325.mediawiki

The empty section should either be removed or filled in

BIP 325: Remove empty section "Acknowledgement"

---

bip-0088.mediawiki

Didn't add the Acknowledgements section in time before the BIP88 was merged, fixing it with this PR.

BIP88: add Acknowledgements section

---

bip-0039.mediawiki

Add an existing reference implementation done in 100% Smalltalk code.

[BIP 39] Add reference implementation

---

bip-0085.mediawiki

The other PR was closed automatically by github: https://github.com/bitcoin/bips/pull/1114

BIP85: Add AirGap Vault implementation

---

bip-0078.mediawiki

See https://github.com/JoinMarket-Org/joinmarket-clientserver/releases/tag/v0.7.1

update Joinmarket BIP78 status

---

bip-0078.mediawiki

the payjoin proposal has more inputs

BIP-0078: fix typo

---

bip-0174.mediawiki
bip-0370.mediawiki

PSBT_OUT_SCRIPT should be 0x04, not 0x03.

psbt2: Fix field number counting

---

README.mediawiki
bip-0174.mediawiki
bip-0371.mediawiki

Specifies new field types and UTXO type semantics for Taproot PSBT fields.

BIP 371: Taproot Fields for PSBT

---

bip-0322.mediawiki

With taproot activated now it should allow for segwit v1

Allow Taproot outputs in BIP 322

---

bip-0380.mediawiki
bip-0381.mediawiki
bip-0382.mediawiki
bip-0383.mediawiki
bip-0384.mediawiki
bip-0385.mediawiki

Minor touch ups in the descriptors BIPs

typo: BIP [380-385]

---

bip-0067.mediawiki

BIP 0067: Fix a broken link

---

bip-0119.mediawiki

@luke-jr these are intended to address your nits on the mailing lists; will work on the more detailed responses later.

[BIP-119] Clarify that policy is not validity + what a covenant is.

---

README.mediawiki
bip-0326.mediawiki
scripts/buildtable.pl

Followup to #1299 to actually fix BIP 326 rather than bypassing CI checks.

Bugfix: BIP 326: Correct Author/Title headings

---

README.mediawiki
bip-0179.mediawiki

179: Remove my email due to spam

---

bip-0119.mediawiki

The level of detail in the motivations for BIP-119 was excessive, this PR removes the lengthy motivation section and adds more links out to various resources.

[BIP-119] Slim down motivation, add more references

---

bip-0039.mediawiki

Added bip-39 dart implementation to the list

bip-39 dart implementation added

---

bip-0039.mediawiki

Add one Swift implementation featured with full native syntax, exception handling & fully unit tested with all supported language wordlists

Add one Swift implementation

---

bip-0039.mediawiki

Add a reference to the JS implementation

Add BIP39 implementation reference

---

bip-0176.mediawiki

Improved the clarity of the "that candy cost me 2 bits" example to make it easier for people to understand the meaning of "2 bits."
Corrected punctuation for "e.g.," and also with quotation mark usage.

Minor improvements

---

bip-0370.mediawiki

Resolves a merge conflict that was accidentally committed in BIP 370. Also fixes a typo.

370: Fix merge conflict and typo

---

bip-0039.mediawiki

Node, Browser, Bun, and Bundler (WebPack, Vite, etc) compatible.

feat: add DashPhrase.js to JS implementations

---

bip-0012.mediawiki

 BIP-12: typo fix 

---

bip-0380.mediawiki
bip-0381.mediawiki
bip-0382.mediawiki
bip-0384.mediawiki

Fix Descriptor BIP typos

---

bip-0039.mediawiki

Links to a zero-dependency, TypeScript BIP39 implementation. Node, browser, Bun, and bundler (Vite, WebPack, etc.) compatible.
(BIP39 Authors: @slush0 @prusnak @voisine @ebfull )

feat: add TypeScript BIP39 implementation

---

bip-0085.mediawiki

Remove duplicate word in bip-0085.mediawiki

---

bip-0141.mediawiki

Originally authored by Greg Laun @greglaun.
When I tried to reopen a prior pull request after closing it, I got the error that "The repository that submitted this pull request has been deleted.". Reopening here to merge.

Fix typos in BIP141

---

bip-0060.mediawiki

minor typo fix
have a nice one

BIP-60: typo fix

---

bip-0042.mediawiki

Bitcoin the network is written with a capital B. The unit is written with small b.

BIP42: Update spelling of bitcoin

---

.gitignore
bip-0174/build.sh
bip-0174/coinjoin-workflow.svg
bip-0174/coinjoin-workflow.tex
bip-0174/multisig-workflow.svg
bip-0174/multisig-workflow.tex

tweaking tkiz arrows for luke-jr with <3

BIP 0174: bring back transparent background to figures

---

bip-0388.mediawiki
bip-0388/wallet_policies.py

Fixes 3 links and makes the reference implementation executable.

BIP388 fixups

---

bip-0114.mediawiki

There are typos in bip-0114, use this change to correct them.

bip-0114: fix typo

---

bip-0340/test-vectors.py

This PR contains minor updates to remove some repeat words from BIP-340.

BIP340: remove repeat words

---

README.mediawiki
bip-0339.mediawiki

This is in active use on the p2p network.

Move BIP 339 to Final

---

bip-0158/gentestvectors.go

BIP158: fix up code comment typo in gentestvectors.go

---

README.mediawiki
bip-0085.mediawiki

Moving this BIP to final stage as this is widely deployed

BIP85: update status to Final

---

README.mediawiki
bip-0345.mediawiki

I don't want the responsibility of championing this proposal (per BIP 2), so would prefer to be removed as co-author.

BIP 345: Remove Anthony Towns as coauthor.

---

bip-0157.mediawiki

Give better clarity for Client Operation

BIP157 grammar fixup: add missing word

---

bip-0373.mediawiki

Per discussion with @jonatack here: https://github.com/bitcoin/bips/pull/1705#discussion_r1879264639

[BIP-373] Slight rewrite of evenness byte footnote for clarity

---

bip-0003.md

- Clarifies that a BIP has to be on-topic to be assigned a number
- Accept phrasing, and punctuation touch-ups from @jonatack’s last review on #1712

BIP3: Address follow-ups from #1712

---

bip-0003.md

A couple of tiny changes as i was reading the BIP from top to bottom. See commit messages for details.

bip3: a couple nits

---

bip-0380.mediawiki

Adding a few minor changes after having read the specs a couple of times.

BIP380: minor grammar fixups

---

bip-0328/_base58.py

BIP328: minor docstring fixups

---

bip-0340.mediawiki

BIP340: fix url to test-vectors.py

---

bip-0374.mediawiki

BIP-0374: fix typo

---

bip-0119.mediawiki

BIP 119: fix link to MES16 paper

---

bip-0373.mediawiki

bip373: add hyperlinks to other BIPs

---

bip-0003.md

Addresses follow-up from https://github.com/bitcoin/bips/pull/1892#issuecomment-3157328596

BIP3: Update License header format on activation
